検証 ひとまず組み合わせなしのパターン

In [98]:
import os
import sys
import numpy as np
import pprint
import pandas as pd
sys.path.append('/Users/otaketomomi/PycharmProjects/PAuth')
pprint.pprint(sys.path)

import numexpr

# 内部ライブラリ
from expmodule.dataset import load_frank
from expmodule.flag_split import flag4
from expmodule.datasplit_train_test_val import datasplit_session
from expmodule.datasplit_train_test_val import x_y_split
# export PYTHONPATH="/path/to/add:$expmodule"`

# warning ignore code
import warnings
warnings.filterwarnings('ignore')

['/Users/otaketomomi/PycharmProjects/PAuth/02_features',
 '/Users/otaketomomi/anaconda3/envs/TF/lib/python37.zip',
 '/Users/otaketomomi/anaconda3/envs/TF/lib/python3.7',
 '/Users/otaketomomi/anaconda3/envs/TF/lib/python3.7/lib-dynload',
 '',
 '/Users/otaketomomi/anaconda3/envs/TF/lib/python3.7/site-packages',
 '/Users/otaketomomi/anaconda3/envs/TF/lib/python3.7/site-packages/IPython/extensions',
 '/Users/otaketomomi/.ipython',
 '/Users/otaketomomi/PycharmProjects/PAuth',
 '/Users/otaketomomi/PycharmProjects/PAuth',
 '/Users/otaketomomi/PycharmProjects/PAuth',
 '/Users/otaketomomi/PycharmProjects/PAuth',
 '/Users/otaketomomi/PycharmProjects/PAuth',
 '/Users/otaketomomi/PycharmProjects/PAuth',
 '/Users/otaketomomi/PycharmProjects/PAuth',
 '/Users/otaketomomi/PycharmProjects/PAuth',
 '/Users/otaketomomi/PycharmProjects/PAuth']

### データの読み込み

In [29]:
frank_df = load_frank(combination=False)
frank_df.head(5)

,user,doc,stroke_inter,stroke_duration,start_x,start_y,stop_x,stop_y,direct_ete_distance,mean_result_leng,...,ave_direction,length_trajectory,ratio_ete,ave_v,5points_m_acc,m_stroke_press,m_stroke_area_cover,finger_orien,cd_finger_orien,phone_orien
0,37,4,0.913,0.086,21.771,-30.037,9.8778,-33.867,12.4950,0.26504,...,-2.199400,12.5960,0.99197,146.470,5117.7,0.600,0.088889,0.0,0,1
1,37,4,0.733,0.111,10.886,-34.169,26.9120,-34.673,16.0340,0.99118,...,0.086288,16.2030,0.98959,145.970,-3563.5,0.480,0.044444,0.0,0,1
2,37,4,0.448,0.094,19.151,-34.572,12.7000,-36.790,6.8213,0.59647,...,-2.723100,6.9674,0.97902,74.122,-4604.1,0.400,0.044444,0.0,0,1
3,37,4,0.519,0.056,27.718,-32.758,14.6150,-37.294,13.8660,0.67819,...,-2.717000,13.8710,0.99965,247.690,-21377.0,0.440,0.044444,0.0,0,1
4,37,4,0.290,0.115,30.137,-30.641,15.8250,-35.479,15.1080,0.79869,...,-2.791400,15.2220,0.99254,132.360,2831.1,0.405,0.044444,0.0,0,1

In [30]:
# Columnの内容の確認
frank_df.columns

Index(['user', 'doc', 'stroke_inter', 'stroke_duration', 'start_x', 'start_y',
       'stop_x', 'stop_y', 'direct_ete_distance', 'mean_result_leng', 'flag',
       'direct_ete_line', '20_pairwise_v', '50_pairwise_v', '80_pairwise_v',
       '20_pairwise_acc', '50_pairwise_acc', '80_pairwise_acc', '3ots_m_v',
       'ete_larg_deviation', '20_ete_line', '50_ete_line', '80_ete_line',
       'ave_direction', 'length_trajectory', 'ratio_ete', 'ave_v',
       '5points_m_acc', 'm_stroke_press', 'm_stroke_area_cover',
       'finger_orien', 'cd_finger_orien', 'phone_orien'],
      dtype='object')

In [31]:
frank_df.shape

(20847, 33)

In [32]:
# flag
frank_df['flag'].unique()

array([4, 2, 3, 1])

In [34]:
frank_df['flag'].value_counts()

3    11102
4     4249
2     4218
1     1278
Name: flag, dtype: int64

In [33]:
# user
frank_df['user'].unique()

array([37,  1, 38,  7, 24,  2, 12, 34,  6, 39, 40, 17, 18,  8, 22, 21, 20,
       19, 33, 23, 14,  3, 31, 27, 16, 41, 25,  4, 35, 36, 32, 29, 30,  5,
       28, 11,  9, 26, 15, 10, 13])

In [80]:
pd.DataFrame(frank_df['user'].value_counts()).sort_index()

    user
1    380
2   1213
3    757
4    226
5    411
6    560
7    584
8    615
9    451
10   385
11   444
12   341
13   305
14   648
15   670
16   380
17   705
18   459
19   292
20   354
21   700
22   369
23   938
24   429
25   410
26   228
27   608
28   697
29   430
30   222
31   367
32   303
33   684
34   607
35  1061
36   492
37   422
38   779
39   429
40   310
41   182

In [193]:
#  frank_df[["user", "doc", "flag"]].groupby(["user", "flag", "doc"]).count().to_csv('../result/info/user_doc_flag_oneclass.csv')
frank_df[["user", "doc", "flag", 'phone_orien']].groupby(["user", "flag", "doc"]).agg(["count"]).to_csv('../result/info/user_doc_flag_oneclass.csv')

In [323]:
frank_df[frank_df['user'] == 35].describe()

,user,doc,stroke_inter,stroke_duration,start_x,start_y,stop_x,stop_y,direct_ete_distance,mean_result_leng,...,ave_direction,length_trajectory,ratio_ete,ave_v,5points_m_acc,m_stroke_press,m_stroke_area_cover,finger_orien,cd_finger_orien,phone_orien
count,1061.0,1061.000000,1061.000000,1061.000000,1061.000000,1061.000000,1061.000000,1061.000000,1061.000000,1061.000000,...,1061.000000,1061.000000,1061.000000,1061.000000,1061.000000,1061.000000,1061.000000,1061.0,1061.0,1061.0
mean,35.0,3.627710,-62.439064,1.537406,16.596462,-39.152672,16.834248,-32.838207,10.808358,0.688105,...,0.230683,13.025596,0.849743,37.889527,590.746483,0.565452,0.047690,0.0,0.0,1.0
std,0.0,2.015025,35659.747810,1.588991,7.834164,5.043455,6.709158,5.333623,5.693934,0.163885,...,1.304426,7.196834,0.178276,49.508644,12118.981153,0.104593,0.018345,0.0,0.0,0.0
min,35.0,1.000000,-594940.000000,0.022000,0.302380,-48.885000,-0.100790,-49.288000,0.100790,0.012488,...,-3.132700,0.100790,0.021069,0.787450,-178570.000000,0.140000,0.044444,0.0,0.0,1.0
25%,35.0,2.000000,1.005000,0.153000,10.180000,-42.333000,11.692000,-36.286000,6.470400,0.602220,...,0.205890,7.863700,0.811970,4.997100,-131.240000,0.500000,0.044444,0.0,0.0,1.0
50%,35.0,3.000000,1.987000,1.107000,17.337000,-41.023000,18.143000,-33.766000,10.081000,0.673730,...,0.597030,11.719000,0.887800,6.560700,0.000000,0.560000,0.044444,0.0,0.0,1.0
75%,35.0,6.000000,3.392000,2.310000,22.376000,-35.782000,22.275000,-30.339000,14.255000,0.749210,...,0.903330,16.532000,0.982450,73.927000,274.870000,0.610000,0.044444,0.0,0.0,1.0
max,35.0,7.000000,594690.000000,10.600000,32.153000,-8.769000,32.758000,-1.814300,39.376000,1.000000,...,3.136200,65.748000,1.000000,227.130000,179050.000000,1.240000,0.355560,0.0,0.0,1.0

## データの分割

 ### 4: flagをもとに想定通りにデータが分割されているかの確認

In [78]:
# 上下左右のflagをもとにデータを分割
a, b, c, d = flag4( frank_df, 'flag')

#### cの比較

In [13]:
# flagの値を変更して分割したあとのものと比較
frank_df.query('flag == 3').head(5)

,user,doc,stroke_inter,stroke_duration,start_x,start_y,stop_x,stop_y,direct_ete_distance,mean_result_leng,...,ave_direction,length_trajectory,ratio_ete,ave_v,5points_m_acc,m_stroke_press,m_stroke_area_cover,finger_orien,cd_finger_orien,phone_orien
137,37,1,1.326,1.073,28.121,-37.394,32.052,-10.684,26.998,0.92509,...,1.3232,28.031,0.96315,26.1240,11611.000000,0.51,0.044444,0.0,0,1
138,37,1,2.934,0.704,25.602,-39.511,27.416,-24.594,15.027,0.68201,...,1.0391,16.212,0.92693,23.0280,0.074442,0.47,0.088889,0.0,0,1
141,37,1,0.686,0.432,27.416,-43.644,30.440,-21.671,22.180,0.63109,...,1.0845,26.002,0.85303,60.1890,-904.790000,0.49,0.044444,0.0,0,1
142,37,1,9.054,0.751,25.299,-44.551,28.222,-28.625,16.191,0.78558,...,1.1723,17.302,0.93580,23.0390,-377.810000,0.44,0.088889,0.0,0,1
143,37,1,11.804,1.734,25.501,-42.233,28.021,-27.013,15.427,0.77228,...,1.1556,16.826,0.91688,9.7034,1.205500,0.41,0.088889,0.0,0,1

In [11]:
c.head(5)

,user,doc,stroke_inter,stroke_duration,start_x,start_y,stop_x,stop_y,direct_ete_distance,mean_result_leng,...,ave_direction,length_trajectory,ratio_ete,ave_v,5points_m_acc,m_stroke_press,m_stroke_area_cover,finger_orien,cd_finger_orien,phone_orien
0,37,1,1.326,1.073,28.121,-37.394,32.052,-10.684,26.998,0.92509,...,1.3232,28.031,0.96315,26.1240,11611.000000,0.51,0.044444,0.0,0,1
1,37,1,2.934,0.704,25.602,-39.511,27.416,-24.594,15.027,0.68201,...,1.0391,16.212,0.92693,23.0280,0.074442,0.47,0.088889,0.0,0,1
2,37,1,0.686,0.432,27.416,-43.644,30.440,-21.671,22.180,0.63109,...,1.0845,26.002,0.85303,60.1890,-904.790000,0.49,0.044444,0.0,0,1
3,37,1,9.054,0.751,25.299,-44.551,28.222,-28.625,16.191,0.78558,...,1.1723,17.302,0.93580,23.0390,-377.810000,0.44,0.088889,0.0,0,1
4,37,1,11.804,1.734,25.501,-42.233,28.021,-27.013,15.427,0.77228,...,1.1556,16.826,0.91688,9.7034,1.205500,0.41,0.088889,0.0,0,1

#### aの比較

In [17]:
frank_df.query('flag == 1').head(5)

,user,doc,stroke_inter,stroke_duration,start_x,start_y,stop_x,stop_y,direct_ete_distance,mean_result_leng,...,ave_direction,length_trajectory,ratio_ete,ave_v,5points_m_acc,m_stroke_press,m_stroke_area_cover,finger_orien,cd_finger_orien,phone_orien
139,37,1,0.830,0.520,27.617,-27.214,25.602,-39.410,12.3620,0.67699,...,-1.587000,14.5840,0.84758,28.047,2656.10,0.48,0.044444,0.0,0,1
140,37,1,2.214,1.728,28.625,-27.214,27.617,-31.548,4.4498,0.55335,...,-0.130080,41.9670,0.10603,24.286,-367.07,0.47,0.044444,0.0,0,1
161,37,1,0.409,0.315,20.763,-40.620,20.562,-45.962,5.3459,0.62236,...,-1.259000,9.7936,0.54585,31.091,9332.60,0.50,0.088889,0.0,0,1
162,37,1,0.625,0.507,25.299,-25.299,20.260,-48.683,23.9210,0.66170,...,-1.383500,25.5890,0.93483,50.471,1861.10,0.56,0.088889,0.0,0,1
163,37,1,7.477,1.177,22.880,-27.718,20.763,-35.177,7.7533,0.35482,...,0.086838,36.1570,0.21443,30.720,1497.70,0.55,0.088889,0.0,0,1

In [14]:
a.head(5)

,user,doc,stroke_inter,stroke_duration,start_x,start_y,stop_x,stop_y,direct_ete_distance,mean_result_leng,...,ave_direction,length_trajectory,ratio_ete,ave_v,5points_m_acc,m_stroke_press,m_stroke_area_cover,finger_orien,cd_finger_orien,phone_orien
0,37,1,0.830,0.520,27.617,-27.214,25.602,-39.410,12.3620,0.67699,...,-1.587000,14.5840,0.84758,28.047,2656.10,0.48,0.044444,0.0,0,1
1,37,1,2.214,1.728,28.625,-27.214,27.617,-31.548,4.4498,0.55335,...,-0.130080,41.9670,0.10603,24.286,-367.07,0.47,0.044444,0.0,0,1
2,37,1,0.409,0.315,20.763,-40.620,20.562,-45.962,5.3459,0.62236,...,-1.259000,9.7936,0.54585,31.091,9332.60,0.50,0.088889,0.0,0,1
3,37,1,0.625,0.507,25.299,-25.299,20.260,-48.683,23.9210,0.66170,...,-1.383500,25.5890,0.93483,50.471,1861.10,0.56,0.088889,0.0,0,1
4,37,1,7.477,1.177,22.880,-27.718,20.763,-35.177,7.7533,0.35482,...,0.086838,36.1570,0.21443,30.720,1497.70,0.55,0.088889,0.0,0,1

#### bの比較

In [18]:
frank_df.query('flag == 2').head(5)

,user,doc,stroke_inter,stroke_duration,start_x,start_y,stop_x,stop_y,direct_ete_distance,mean_result_leng,...,ave_direction,length_trajectory,ratio_ete,ave_v,5points_m_acc,m_stroke_press,m_stroke_area_cover,finger_orien,cd_finger_orien,phone_orien
1,37,4,0.733,0.111,10.8860,-34.169,26.912,-34.673,16.0340,0.99118,...,0.086288,16.2030,0.98959,145.970,-3563.500,0.480,0.044444,0.0,0,1
8,37,4,0.220,0.045,12.0950,-31.952,16.429,-32.456,4.3633,0.99472,...,-0.033020,4.3996,0.99175,97.770,-14737.000,0.380,0.044444,0.0,0,1
9,37,4,1.907,0.128,10.6840,-33.262,29.936,-35.883,19.4290,0.99677,...,-0.099446,19.4440,0.99922,151.910,12.421,0.560,0.044444,0.0,0,1
10,37,4,11.949,0.157,7.1563,-30.944,27.013,-31.750,19.8730,0.96582,...,0.102100,19.9920,0.99405,127.340,2496.000,0.550,0.044444,0.0,0,1
13,37,4,0.342,0.136,9.7770,-36.991,18.949,-36.185,9.2076,0.91172,...,0.310860,10.0140,0.91943,73.635,6932.400,0.605,0.044444,0.0,0,1

In [15]:
b.head(5)

,user,doc,stroke_inter,stroke_duration,start_x,start_y,stop_x,stop_y,direct_ete_distance,mean_result_leng,...,ave_direction,length_trajectory,ratio_ete,ave_v,5points_m_acc,m_stroke_press,m_stroke_area_cover,finger_orien,cd_finger_orien,phone_orien
0,37,4,0.733,0.111,10.8860,-34.169,26.912,-34.673,16.0340,0.99118,...,0.086288,16.2030,0.98959,145.970,-3563.500,0.480,0.044444,0.0,0,1
1,37,4,0.220,0.045,12.0950,-31.952,16.429,-32.456,4.3633,0.99472,...,-0.033020,4.3996,0.99175,97.770,-14737.000,0.380,0.044444,0.0,0,1
2,37,4,1.907,0.128,10.6840,-33.262,29.936,-35.883,19.4290,0.99677,...,-0.099446,19.4440,0.99922,151.910,12.421,0.560,0.044444,0.0,0,1
3,37,4,11.949,0.157,7.1563,-30.944,27.013,-31.750,19.8730,0.96582,...,0.102100,19.9920,0.99405,127.340,2496.000,0.550,0.044444,0.0,0,1
4,37,4,0.342,0.136,9.7770,-36.991,18.949,-36.185,9.2076,0.91172,...,0.310860,10.0140,0.91943,73.635,6932.400,0.605,0.044444,0.0,0,1

#### dの比較

In [19]:
frank_df.query('flag == 4').head(5)

,user,doc,stroke_inter,stroke_duration,start_x,start_y,stop_x,stop_y,direct_ete_distance,mean_result_leng,...,ave_direction,length_trajectory,ratio_ete,ave_v,5points_m_acc,m_stroke_press,m_stroke_area_cover,finger_orien,cd_finger_orien,phone_orien
0,37,4,0.913,0.086,21.771,-30.037,9.8778,-33.867,12.4950,0.26504,...,-2.1994,12.5960,0.99197,146.470,5117.7,0.600,0.088889,0.0,0,1
2,37,4,0.448,0.094,19.151,-34.572,12.7000,-36.790,6.8213,0.59647,...,-2.7231,6.9674,0.97902,74.122,-4604.1,0.400,0.044444,0.0,0,1
3,37,4,0.519,0.056,27.718,-32.758,14.6150,-37.294,13.8660,0.67819,...,-2.7170,13.8710,0.99965,247.690,-21377.0,0.440,0.044444,0.0,0,1
4,37,4,0.290,0.115,30.137,-30.641,15.8250,-35.479,15.1080,0.79869,...,-2.7914,15.2220,0.99254,132.360,2831.1,0.405,0.044444,0.0,0,1
5,37,4,1.001,0.091,22.376,-32.355,11.3900,-33.967,11.1040,0.74862,...,-2.9566,11.1380,0.99700,122.390,-4931.1,0.500,0.044444,0.0,0,1

In [16]:
d.head(5)

,user,doc,stroke_inter,stroke_duration,start_x,start_y,stop_x,stop_y,direct_ete_distance,mean_result_leng,...,ave_direction,length_trajectory,ratio_ete,ave_v,5points_m_acc,m_stroke_press,m_stroke_area_cover,finger_orien,cd_finger_orien,phone_orien
0,37,4,0.913,0.086,21.771,-30.037,9.8778,-33.867,12.4950,0.26504,...,-2.1994,12.5960,0.99197,146.470,5117.7,0.600,0.088889,0.0,0,1
1,37,4,0.448,0.094,19.151,-34.572,12.7000,-36.790,6.8213,0.59647,...,-2.7231,6.9674,0.97902,74.122,-4604.1,0.400,0.044444,0.0,0,1
2,37,4,0.519,0.056,27.718,-32.758,14.6150,-37.294,13.8660,0.67819,...,-2.7170,13.8710,0.99965,247.690,-21377.0,0.440,0.044444,0.0,0,1
3,37,4,0.290,0.115,30.137,-30.641,15.8250,-35.479,15.1080,0.79869,...,-2.7914,15.2220,0.99254,132.360,2831.1,0.405,0.044444,0.0,0,1
4,37,4,1.001,0.091,22.376,-32.355,11.3900,-33.967,11.1040,0.74862,...,-2.9566,11.1380,0.99700,122.390,-4931.1,0.500,0.044444,0.0,0,1

大丈夫そう

In [20]:
user_n = 23

### 5: flagごとに選択されたユーザがきちんと抽出されているかを確かめる

In [21]:
# flagごとに選択したユーザを抽出する
def select_user_flag(df_flag, u_n, text):
    # フォルダがなければ自動的に作成
#     os.makedirs('result/info', exist_ok=True)
    df_flag_user_extract = df_flag[df_flag['user'] == u_n]
    # Comment: 1-41人全員分行ったらコメントアウト
    data_item = pd.DataFrame([u_n, text, len(df_flag_user_extract)]).T
    print(data_item)
#     data_item.to_csv(f'result/info/main_oneclass_df_flag_user_extract_item.csv', mode='a', header=None, index=None)
    return df_flag_user_extract

In [24]:
a_user_extract = select_user_flag(a, user_n, 'a')
a_user_extract.head(5)

    0  1    2
0  23  a  146

,user,doc,stroke_inter,stroke_duration,start_x,start_y,stop_x,stop_y,direct_ete_distance,mean_result_leng,...,ave_direction,length_trajectory,ratio_ete,ave_v,5points_m_acc,m_stroke_press,m_stroke_area_cover,finger_orien,cd_finger_orien,phone_orien
635,23,1,0.521,0.081,21.803,-27.144,17.987,-44.150,17.4290,0.73306,...,-1.4460,17.5580,0.99263,216.770,-2210.90,0.18039,0.066667,0.0,0,1
636,23,1,0.869,0.068,19.404,-32.050,17.769,-42.079,10.1620,0.69939,...,-1.2263,10.1790,0.99825,149.700,-8243.20,0.14902,0.044444,0.0,0,1
637,23,1,1.845,0.075,21.367,-29.542,18.750,-44.150,14.8400,0.74222,...,-1.3903,15.0570,0.98560,200.760,-7286.00,0.18039,0.066667,0.0,0,1
638,23,1,1.782,0.292,23.547,-26.381,21.476,-31.396,5.4255,0.60520,...,-1.3146,5.6540,0.95959,19.363,-966.34,0.20784,0.088889,0.0,0,1
639,23,1,1.914,0.354,20.058,-30.306,19.949,-39.572,9.2667,0.81758,...,-1.4314,9.9819,0.92836,28.197,-1004.20,0.23922,0.088889,0.0,0,1

In [26]:
b_user_extract = select_user_flag(b, user_n, 'b')
b_user_extract.head(5)

    0  1    2
0  23  b  171

,user,doc,stroke_inter,stroke_duration,start_x,start_y,stop_x,stop_y,direct_ete_distance,mean_result_leng,...,ave_direction,length_trajectory,ratio_ete,ave_v,5points_m_acc,m_stroke_press,m_stroke_area_cover,finger_orien,cd_finger_orien,phone_orien
1918,23,4,0.521,0.116,10.9010,-37.391,31.723,-36.628,20.835,0.99570,...,0.056467,20.949,0.99460,180.59,-2210.1,0.18039,0.077778,0.0,0,1
1919,23,4,1.031,0.144,11.0100,-37.936,32.268,-36.083,21.338,0.99293,...,0.093942,21.492,0.99285,149.25,2798.5,0.16471,0.066667,0.0,0,1
1920,23,4,0.541,0.143,8.5030,-41.316,33.140,-37.391,24.948,0.99421,...,0.129540,25.050,0.99592,175.17,-2267.9,0.15294,0.066667,0.0,0,1
1921,23,4,1.675,0.129,7.6309,-40.553,32.377,-36.083,25.146,0.99240,...,0.143240,25.332,0.99268,196.37,-5564.2,0.14118,0.088889,0.0,0,1
1922,23,4,0.419,0.101,11.3370,-36.301,23.765,-28.016,14.936,0.96674,...,0.446810,14.954,0.99880,148.06,-4421.8,0.34902,0.211110,0.0,0,1

In [27]:
c_user_extract = select_user_flag(c, user_n, 'c')
c_user_extract.head(5)

    0  1    2
0  23  c  456

,user,doc,stroke_inter,stroke_duration,start_x,start_y,stop_x,stop_y,direct_ete_distance,mean_result_leng,...,ave_direction,length_trajectory,ratio_ete,ave_v,5points_m_acc,m_stroke_press,m_stroke_area_cover,finger_orien,cd_finger_orien,phone_orien
5748,23,4,2.074,0.190,34.121,-46.767,34.121,-37.173,9.5931,0.62924,...,1.3897,9.8564,0.97329,51.876,-1419.90,0.07451,0.055556,0.0,0,1
5749,23,1,2.060,0.337,27.907,-44.259,28.997,-30.633,13.6700,0.84380,...,1.0878,13.9350,0.98096,41.351,14294.00,0.21176,0.088889,0.0,0,1
5750,23,1,0.955,0.420,26.490,-44.368,27.907,-29.324,15.1100,0.92650,...,1.3388,15.4640,0.97711,36.820,305.03,0.25098,0.122220,0.0,0,1
5751,23,1,9.884,0.389,27.689,-49.165,27.035,-40.989,8.2021,0.91962,...,1.5889,8.3294,0.98471,21.412,460.02,0.22353,0.100000,0.0,0,1
5752,23,1,0.565,0.140,26.708,-45.676,25.727,-29.870,15.8370,0.84246,...,1.4974,16.0020,0.98973,114.300,1861.70,0.20392,0.088889,0.0,0,1

In [28]:
d_user_extract = select_user_flag(d, user_n, 'd')
d_user_extract.head(5)

    0  1    2
0  23  d  165

,user,doc,stroke_inter,stroke_duration,start_x,start_y,stop_x,stop_y,direct_ete_distance,mean_result_leng,...,ave_direction,length_trajectory,ratio_ete,ave_v,5points_m_acc,m_stroke_press,m_stroke_area_cover,finger_orien,cd_finger_orien,phone_orien
1931,23,4,2.066,0.123,28.343,-39.790,16.5700,-42.297,12.0370,0.50561,...,-2.8312,12.0770,0.99673,98.186,-2394.00,0.14510,0.055556,0.0,0,1
1932,23,4,0.867,0.141,30.088,-32.813,5.8867,-43.496,26.4540,0.61080,...,-2.6408,26.6740,0.99176,189.180,-480.18,0.15686,0.066667,0.0,0,1
1933,23,4,0.700,0.124,28.997,-32.159,6.8678,-39.572,23.3380,0.60467,...,-2.7581,23.5610,0.99054,190.010,-4552.00,0.16863,0.088889,0.0,0,1
1934,23,4,0.414,0.107,27.035,-39.354,18.5320,-37.936,8.6203,0.50552,...,2.8813,8.6218,0.99983,80.577,106.96,0.22745,0.111110,0.0,0,1
1935,23,4,0.768,0.070,22.893,-30.306,11.9910,-36.083,12.3380,0.54098,...,-2.4279,12.3690,0.99745,176.700,-6366.10,0.24314,0.111110,0.0,0,1

大丈夫そう

In [85]:
# result/info/main_oneclass_df_flag_user_extract_item.csv'への書き出し用
for u_n in range(1,42):
    a_user_extract = select_user_flag(a, u_n, 'a')
    b_user_extract = select_user_flag(b, u_n, 'b')
    c_user_extract = select_user_flag(c, u_n, 'c')
    d_user_extract = select_user_flag(d, u_n, 'd')

   0  1  2
0  1  a  9
   0  1   2
0  1  b  63
   0  1    2
0  1  c  245
   0  1   2
0  1  d  63
   0  1   2
0  2  a  49
   0  1    2
0  2  b  119
   0  1    2
0  2  c  928
   0  1    2
0  2  d  117
   0  1   2
0  3  a  62
   0  1    2
0  3  b  162
   0  1    2
0  3  c  372
   0  1    2
0  3  d  161
   0  1  2
0  4  a  4
   0  1   2
0  4  b  58
   0  1   2
0  4  c  94
   0  1   2
0  4  d  70
   0  1   2
0  5  a  34
   0  1   2
0  5  b  93
   0  1    2
0  5  c  196
   0  1   2
0  5  d  88
   0  1   2
0  6  a  31
   0  1    2
0  6  b  144
   0  1    2
0  6  c  244
   0  1    2
0  6  d  141
   0  1   2
0  7  a  79
   0  1    2
0  7  b  107
   0  1    2
0  7  c  294
   0  1    2
0  7  d  104
   0  1   2
0  8  a  21
   0  1    2
0  8  b  198
   0  1    2
0  8  c  202
   0  1    2
0  8  d  194
   0  1   2
0  9  a  22
   0  1    2
0  9  b  108
   0  1    2
0  9  c  211
   0  1    2
0  9  d  110
    0  1   2
0  10  a  10
    0  1    2
0  10  b  108
    0  1    2
0  10  c  157
    0  1    2
0  10  d  110
    0  1   2
0  11  a  11
    0  1    2
0  11  b  154
    0  1    2
0  11  c  120
    0  1    2
0  11  d  159
    0  1  2
0  12  a  1
    0  1    2
0  12  b  100
    0  1    2
0  12  c  139
    0  1    2
0  12  d  101
    0  1   2
0  13  a  13
    0  1   2
0  13  b  81
    0  1    2
0  13  c  139
    0  1   2
0  13  d  72
    0  1   2
0  14  a  56
    0  1    2
0  14  b  140
    0  1    2
0  14  c  321
    0  1    2
0  14  d  131
    0  1   2
0  15  a  81
    0  1    2
0  15  b  150
    0  1    2
0  15  c  314
    0  1    2
0  15  d  125
    0  1  2
0  16  a  5
    0  1    2
0  16  b  125
    0  1    2
0  16  c  117
    0  1    2
0  16  d  133
    0  1   2
0  17  a  10
    0  1    2
0  17  b  113
    0  1    2
0  17  c  463
    0  1    2
0  17  d  119
    0  1   2
0  18  a  11
    0  1   2
0  18  b  89
    0  1    2
0  18  c  274
    0  1   2
0  18  d  85
    0  1   2
0  19  a  48
    0  1   2
0  19  b  64
    0  1    2
0  19  c  113
    0  1   2
0  19  d  67
    0  1   2
0  20  a  18
    0  1    2
0  20  b  110
    0  1    2
0  20  c  116
    0  1    2
0  20  d  110
    0  1   2
0  21  a  45
    0  1    2
0  21  b  117
    0  1    2
0  21  c  419
    0  1    2
0  21  d  119
    0  1   2
0  22  a  45
    0  1   2
0  22  b  62
    0  1    2
0  22  c  196
    0  1   2
0  22  d  66
    0  1    2
0  23  a  146
    0  1    2
0  23  b  171
    0  1    2
0  23  c  456
    0  1    2
0  23  d  165
    0  1   2
0  24  a  64
    0  1   2
0  24  b  78
    0  1    2
0  24  c  212
    0  1   2
0  24  d  75
    0  1   2
0  25  a  43
    0  1   2
0  25  b  70
    0  1    2
0  25  c  225
    0  1   2
0  25  d  72
    0  1   2
0  26  a  26
    0  1   2
0  26  b  25
    0  1    2
0  26  c  141
    0  1   2
0  26  d  36
    0  1   2
0  27  a  17
    0  1    2
0  27  b  152
    0  1    2
0  27  c  293
    0  1    2
0  27  d  146
    0  1   2
0  28  a  31
    0  1    2
0  28  b  126
    0  1    2
0  28  c  409
    0  1    2
0  28  d  131
    0  1  2
0  29  a  5
    0  1    2
0  29  b  106
    0  1    2
0  29  c  211
    0  1    2
0  29  d  108
    0  1   2
0  30  a  23
    0  1   2
0  30  b  24
    0  1    2
0  30  c  150
    0  1   2
0  30  d  25
    0  1  2
0  31  a  9
    0  1   2
0  31  b  79
    0  1    2
0  31  c  204
    0  1   2
0  31  d  75
    0  1  2
0  32  a  5
    0  1   2
0  32  b  85
    0  1    2
0  32  c  123
    0  1   2
0  32  d  90
    0  1   2
0  33  a  53
    0  1    2
0  33  b  164
    0  1    2
0  33  c  293
    0  1    2
0  33  d  174
    0  1  2
0  34  a  7
    0  1   2
0  34  b  27
    0  1    2
0  34  c  543
    0  1   2
0  34  d  30
    0  1   2
0  35  a  13
    0  1    2
0  35  b  161
    0  1    2
0  35  c  707
    0  1    2
0  35  d  180
    0  1   2
0  36  a  23
    0  1   2
0  36  b  69
    0  1    2
0  36  c  328
    0  1   2
0  36  d  72
    0  1   2
0  37  a  17
    0  1    2
0  37  b  122
    0  1    2
0  37  c  155
    0  1    2
0  37  d  128
    0  1   2
0  38  a  91
    0  1    2
0  38  b  104
    0  1    2
0  38  c  489
    0  1   2
0  38  d  95
    0  1   2
0  39  a  28
    0  1   2
0  39  b  77
    0  1    2
0  39  c  244
    0  1   2
0  39  d  80
    0  1  2
0  40  a  8
    0  1   2
0  40  b  60
    0  1    2
0  40  c  179
    0  1   2
0  40  d  63
    0  1  2
0  41  a  4
    0  1   2
0  41  b  53
    0  1   2
0  41  c  66
    0  1   2
0  41  d  59

In [ ]:
# 仕切り直し

In [94]:
a_user_extract = select_user_flag(a, user_n, 'a')
b_user_extract = select_user_flag(b, user_n, 'b')
c_user_extract = select_user_flag(c, user_n, 'c')
d_user_extract = select_user_flag(d, user_n, 'd')

    0  1    2
0  23  a  146
    0  1    2
0  23  b  171
    0  1    2
0  23  c  456
    0  1    2
0  23  d  165

### 7: flagごとのdocの内訳をみる

In [8]:
def doc_conform(df_flag):
    for i in range(1, 42):
        doc_list = df_flag['doc'].value_counts().index.tolist()
        print(f'{i}:{sorted(doc_list)}')

In [ ]:
doc_conform(a)

In [ ]:
doc_conform(b)

In [170]:
doc_conform(c)

1:[1, 2, 3, 4, 5, 6, 7]
2:[1, 2, 3, 4, 5, 6, 7]
3:[1, 2, 3, 4, 5, 6, 7]
4:[1, 2, 3, 4, 5, 6, 7]
5:[1, 2, 3, 4, 5, 6, 7]
6:[1, 2, 3, 4, 5, 6, 7]
7:[1, 2, 3, 4, 5, 6, 7]
8:[1, 2, 3, 4, 5, 6, 7]
9:[1, 2, 3, 4, 5, 6, 7]
10:[1, 2, 3, 4, 5, 6, 7]
11:[1, 2, 3, 4, 5, 6, 7]
12:[1, 2, 3, 4, 5, 6, 7]
13:[1, 2, 3, 4, 5, 6, 7]
14:[1, 2, 3, 4, 5, 6, 7]
15:[1, 2, 3, 4, 5, 6, 7]
16:[1, 2, 3, 4, 5, 6, 7]
17:[1, 2, 3, 4, 5, 6, 7]
18:[1, 2, 3, 4, 5, 6, 7]
19:[1, 2, 3, 4, 5, 6, 7]
20:[1, 2, 3, 4, 5, 6, 7]
21:[1, 2, 3, 4, 5, 6, 7]
22:[1, 2, 3, 4, 5, 6, 7]
23:[1, 2, 3, 4, 5, 6, 7]
24:[1, 2, 3, 4, 5, 6, 7]
25:[1, 2, 3, 4, 5, 6, 7]
26:[1, 2, 3, 4, 5, 6, 7]
27:[1, 2, 3, 4, 5, 6, 7]
28:[1, 2, 3, 4, 5, 6, 7]
29:[1, 2, 3, 4, 5, 6, 7]
30:[1, 2, 3, 4, 5, 6, 7]
31:[1, 2, 3, 4, 5, 6, 7]
32:[1, 2, 3, 4, 5, 6, 7]
33:[1, 2, 3, 4, 5, 6, 7]
34:[1, 2, 3, 4, 5, 6, 7]
35:[1, 2, 3, 4, 5, 6, 7]
36:[1, 2, 3, 4, 5, 6, 7]
37:[1, 2, 3, 4, 5, 6, 7]
38:[1, 2, 3, 4, 5, 6, 7]
39:[1, 2, 3, 4, 5, 6, 7]
40:[1, 2, 3, 4, 5, 6, 7]
41:[1, 2, 3, 4, 5, 6, 7]

In [9]:
doc_conform(d)

1:[1, 2, 3, 4, 5, 6, 7]
2:[1, 2, 3, 4, 5, 6, 7]
3:[1, 2, 3, 4, 5, 6, 7]
4:[1, 2, 3, 4, 5, 6, 7]
5:[1, 2, 3, 4, 5, 6, 7]
6:[1, 2, 3, 4, 5, 6, 7]
7:[1, 2, 3, 4, 5, 6, 7]
8:[1, 2, 3, 4, 5, 6, 7]
9:[1, 2, 3, 4, 5, 6, 7]
10:[1, 2, 3, 4, 5, 6, 7]
11:[1, 2, 3, 4, 5, 6, 7]
12:[1, 2, 3, 4, 5, 6, 7]
13:[1, 2, 3, 4, 5, 6, 7]
14:[1, 2, 3, 4, 5, 6, 7]
15:[1, 2, 3, 4, 5, 6, 7]
16:[1, 2, 3, 4, 5, 6, 7]
17:[1, 2, 3, 4, 5, 6, 7]
18:[1, 2, 3, 4, 5, 6, 7]
19:[1, 2, 3, 4, 5, 6, 7]
20:[1, 2, 3, 4, 5, 6, 7]
21:[1, 2, 3, 4, 5, 6, 7]
22:[1, 2, 3, 4, 5, 6, 7]
23:[1, 2, 3, 4, 5, 6, 7]
24:[1, 2, 3, 4, 5, 6, 7]
25:[1, 2, 3, 4, 5, 6, 7]
26:[1, 2, 3, 4, 5, 6, 7]
27:[1, 2, 3, 4, 5, 6, 7]
28:[1, 2, 3, 4, 5, 6, 7]
29:[1, 2, 3, 4, 5, 6, 7]
30:[1, 2, 3, 4, 5, 6, 7]
31:[1, 2, 3, 4, 5, 6, 7]
32:[1, 2, 3, 4, 5, 6, 7]
33:[1, 2, 3, 4, 5, 6, 7]
34:[1, 2, 3, 4, 5, 6, 7]
35:[1, 2, 3, 4, 5, 6, 7]
36:[1, 2, 3, 4, 5, 6, 7]
37:[1, 2, 3, 4, 5, 6, 7]
38:[1, 2, 3, 4, 5, 6, 7]
39:[1, 2, 3, 4, 5, 6, 7]
40:[1, 2, 3, 4, 5, 6, 7]
41:[1, 2, 3, 4, 5, 6, 7]

In [ ]:
# 第2段階

In [90]:
# スケーリング
from sklearn import preprocessing

# モデル
from sklearn.svm import OneClassSVM
from sklearn.ensemble import IsolationForest
from sklearn.covariance import EllipticEnvelope
from sklearn.neighbors import LocalOutlierFactor

# 交差検証
from sklearn.model_selection import KFold

# 評価指標
from sklearn.metrics import f1_score
from sklearn.metrics import recall_score
from sklearn.metrics import roc_auc_score
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score

#### far_frr_berの関数

In [86]:
def far_frr_ber(normal_result, anomaly_result):
    tp = np.count_nonzero(normal_result == 1)
    fn = np.count_nonzero(normal_result == -1)
    fp = np.count_nonzero(anomaly_result == 1)
    tn = np.count_nonzero(anomaly_result == -1)
    re_far = fp / (tn + fp)
    re_frr = fn / (fn + tp)
    re_ber = 0.5 * ((fp / (tn + fp)) + (fn / (fn + tp)))

    # accuracy = ((TP+TN)/(TP+FN+FP+TN))
    # print(accuracy)
    return re_far, re_frr, re_ber

#### 検証用データに外れ値を付与する

In [87]:
def fake_val(df_flag, x_val_t, y_val_t, u_n, x_train, columns, fake_data_except_test_f):
    """
    :param df_flag: multi_flagに基づいた各データの集まり
    :param x_val_t: X_train_ssの内の検証用データ
    :param y_val_t: Y_train_ssの内の検証用データ
    :param u_n: ユーザの番号
    :param x_train: 各フラグのうちuser_nで抽出されたX_trainのスケーリング前のもの
    スケーリングの範囲を合わせるために利用
    :param columns: Column
    :param fake_data_except_test_f: fake_data_except_test_f
    :return: 外れ値を付与した検証用データ
    """

    # 検証用データの個数調査
    val_t_size = y_val_t.count()
    # テスト用に使用する他人のデータ以外から検証用データと同じ数選択する
    val_outlier = fake_data_except_test_f[:val_t_size]

    # print(val_outlier)

    val_outlier_user_n = list(val_outlier['user'])
    # print(val_outlier_user_n)
    val_outlier2 = val_outlier.copy()
    val_outlier_user_change0 = val_outlier2.replace({'user': val_outlier_user_n}, 0)
    # print(val_outlier_user_change0)

    x_val_f, y_val_f = x_y_split(val_outlier_user_change0)

    # スケーリング
    ss = preprocessing.StandardScaler()
    ss.fit(x_train)
    x_val_f_ss = ss.transform(x_val_f)
    x_val_f_ss_df = pd.DataFrame(x_val_f_ss)
    x_val_f_ss_df.columns = columns

    # testデータの結合
    x_val = pd.concat([x_val_t, x_val_f_ss_df]).reset_index(drop=True)
    y_val = pd.concat([y_val_t, y_val_f]).reset_index(drop=True)

    # print(y_val)

    y_val2 = y_val.copy()
    # 結果が本人であれば１，偽物であれば-1で返されるため，予測された結果があっているかを確認するための教師データを作成する
    y_val_true = y_val2.replace({u_n: 1, 0: -1})

    return x_val, y_val_true, x_val_t, x_val_f_ss_df

In [239]:
import pandas as pd
from sklearn.model_selection import train_test_split


def x_y_split(df_flag_user_extract):
    x_split = df_flag_user_extract.drop("user", 1)
    y_split = df_flag_user_extract.user
    return x_split, y_split


# 偽物(外れ値)のデータの選択
def _outlier(df_flag, user_n, y_test_t_size):
    # user_n以外のuserを抽出
    # print(df_flag.shape) # (146, 31)
    fake_data = df_flag[df_flag['user'] != user_n]
    # print(fake_data.shape) # (0, 31)
    # シャッフル
    fake_data_shuffle = fake_data.sample(frac=1, random_state=0).reset_index(drop=True)
    # testデータと同じ数の外れ値を選択
    # outlier = fake_data_shuffle.sample(n=y_test_t_size, random_state=0)
    fake_data_except_outlier = fake_data_shuffle[y_test_t_size:]
    outlier = fake_data_shuffle[:y_test_t_size]

    # print(fake_data_except_outlier.shape)
    # print(outlier.shape)
    return fake_data_except_outlier, outlier


# testデータと外れ値データの結合
def _tf_concat(x_test_t, y_test_t, test_f):
    # outlier == test_f
    test_f_user_n = list(test_f['user'])
    # userをすべて０に変更
    test_f2 = test_f.copy()
    test_f_user_n_change0 = test_f2.replace({'user': test_f_user_n}, 0)
    # print(test_f_user_n_change0.shape) # (0, 31)
    # 偽物のデータを説明変数と目的変数に分割
    x_test_f, y_test_f = x_y_split(test_f_user_n_change0)
    # print(x_test_f.shape) # (0, 30)

    # testデータの結合
    x_test = pd.concat([x_test_t, x_test_f]).reset_index(drop=True)
    y_test = pd.concat([y_test_t, y_test_f]).reset_index(drop=True)

    return x_test, y_test, x_test_f, y_test_f


def _train_test(df_flag, df_flag_user_extract, user_n, test_size, train_size):
    if df_flag_user_extract['user'].count() >= 50:
        # 説明変数と目的変数に分割
        x, y = x_y_split(df_flag_user_extract)

        # その他のデータとテスト用(認証用)データに切り分け
        x_train_all, x_test_t, y_train_all, y_test_t = train_test_split(x, y, test_size=test_size, random_state=0,
                                                                        shuffle=True)
        # 学習用データとその他のデータ2に切り分け
        x_train, x_others, y_train, y_others = train_test_split(x_train_all, y_train_all, train_size=train_size,
                                                                random_state=0, shuffle=True)
        # テストデータの個数をカウント➝外れ値はテストデータ数と同じ数だけ用意する
        # _outlinerの呼び出し
        fake_data, test_f = _outlier(df_flag, user_n, test_size)

        # test_tとtest_fの結合
        x_test, y_test, x_test_f, y_test_f = _tf_concat(x_test_t, y_test_t, test_f)

        return x_train, y_train, x_test, y_test

    else:
        print('None')
        return 0, 0, 0, 0
        pass

def doc_conform(df_flag):
    for i in range(1, 42):
        doc_list = df_flag['doc'].value_counts().index.tolist()
        print(f'{i}:{sorted(doc_list)}')

# AttributeErrorで例外処理に引っかかることを祈る
def datasplit_session_test(df_flag, df_flag_user_extract, user_n, session_select='all', train_size=40, test_size=10):
    df_session = df_flag_user_extract.copy()
    print(f'df_flag_user_extractに含まれるdocの値: ')
    print(df_session['doc'].unique())
    print(f'session_select: {session_select}')
    # df_flag_data = df_flag.copy()
    # docが1~5のもの
    if session_select == 'first':
        df_first_pre = df_session.query('1<= doc < 6')
        print(f'df_first_preに含まれるdocの値: ')
        print(df_first_pre['doc'].unique())
        
        df_flag_data = df_flag.query('1<= doc < 8')
        print(f'df_flag_dataに含まれるdocの値: ')
        print(df_flag_data['doc'].unique())
        
        print(f'colunmsの数を確認する(df_first_pre): {df_first_pre.shape}')
        
        # docの役目は終わったので消去
        df_first = df_first_pre.drop('doc', axis=1)
        df_flag_pre = df_flag_data.drop('doc', axis=1)
        # TODO: colunmsの数を確認する
        if df_first['user'].count() >= (train_size + test_size):
            print(f'colunmsの数を確認する(df_first): {df_first.shape}')
            # 説明変数と目的変数に分割
            print(f'df_first:{df_first.head()}')
            x, y = x_y_split(df_first)
            print(f'x: {x.iloc[:3, [0, 1]]}')
            print(f'y: {y}')
            print(f'x_shape: {x.shape}')

            # その他のデータとテスト用(認証用)データに切り分け
            x_train_all, x_test_t, y_train_all, y_test_t = train_test_split(x, y, test_size=test_size, random_state=0,
                                                                            shuffle=True)
            print(f'x_train_all:\n {x_train_all.iloc[:3, [0, 1]]}')
            print(f'y_train_all:\n {y_train_all}')
            print(f'x_train_all_shape:\n {x_train_all.shape}')
            print(f'y_train_all_len:\n {len(y_train_all)}')
            print(f'x_test_t:\n {x_test_t.iloc[:3, [0, 1]]}')
            print(f'y_test_t:\n {y_test_t}')
            print(f'x_test_t_shape:\n {x_test_t.shape}')
            print(f'y_test_t_len:\n {len(y_test_t)}')
            
            # 学習用データとその他のデータ2に切り分け
            x_train, x_others, y_train, y_others = train_test_split(x_train_all, y_train_all, train_size=train_size,
                                                                    random_state=0, shuffle=True)
            
            print(f'x_train:\n {x_train.iloc[:3, [0, 1]]}')
            print(f'y_train:\n {y_train}')
            print(f'x_train_shape:\n {x_train.shape}')
            print(f'y_train_len:\n {len(y_train)}')
            print(f'x_others:\n {x_others.iloc[:3, [0, 1]]}')
            print(f'y_others:\n {y_others}')
            print(f'x_others_shape:\n {x_others.shape}')
            print(f'y_others_len:\n {len(y_others)}')
            
            
            # テストデータの個数をカウント➝外れ値はテストデータ数と同じ数だけ用意する
            # _outlinerの呼び出し
            fake_data_except_test_f, test_f = _outlier(df_flag_pre, user_n, test_size)
            print(f'fake_data_except_test_f:\n{fake_data_except_test_f.iloc[:3, [0, 1]]}')
            print(f'test_f:\n{test_f.iloc[:3, [0, 1]]}')

            # test_tとtest_fの結合
            x_test, y_test, x_test_f, y_test_f = _tf_concat(x_test_t, y_test_t, test_f)
            
            print(f'x_test:\n {x_test.iloc[:3, [0, 1]]}')
            print(f'y_test:\n {y_test}')
            print(f'x_test_shape:\n {x_test.shape}')
            print(f'y_test_len:\n {len(y_test)}')
            print(f'x_test_f:\n {x_test_f.iloc[:3, [0, 1]]}')
            print(f'y_test_f:\n {y_test_f}')
            print(f'x_test_f_shape:\n {x_test_f.shape}')
            print(f'y_test_f_len:\n {len(y_test_f)}')

            return x_train, y_train, x_test, y_test, x_test_t, y_test_t, x_test_f, y_test_f, test_f, \
                fake_data_except_test_f

        else:
            print('None')
            return 0, 0, 0, 0, 0, 0, 0, 0, 0

    # docが6or7のもの
    elif session_select == 'latter':
#         df_session2 = df_session.query('6 <= doc < 8')
        df_first_pre = df_session.query('1<= doc < 6')
        df_latter_pre = df_session.query('6 <= doc < 8')
        df_flag_data = df_flag.query('1 <= doc < 8')
        # docの役目は終わったので消去
        df_first = df_first_pre.drop('doc', axis=1)
        df_latter = df_latter_pre.drop('doc', axis=1)
        df_flag_pre = df_flag_data.drop('doc', axis=1)
        if df_first['user'].count() >= train_size and df_latter['user'].count() >= test_size:
            # 説明変数と目的変数に分割
            x_first, y_first = x_y_split(df_first)
            x_latter, y_latter = x_y_split(df_latter)

            x_other_latter, x_test_t, y_other_latter, y_test_t = train_test_split(x_latter, y_latter,
                                                                                  test_size=test_size,
                                                                                  random_state=0, shuffle=True)
            x_train, x_other_first, y_train, y_other_first = train_test_split(x_first, y_first, train_size=train_size,
                                                                              random_state=0, shuffle=True)
            fake_data_except_test_f, test_f = _outlier(df_flag_pre, user_n, test_size)
            x_test, y_test, x_test_f, y_test_f = _tf_concat(x_test_t, y_test_t, test_f)

            return x_train, y_train, x_test, y_test, x_test_t, y_test_t, x_test_f, y_test_f, test_f, \
                fake_data_except_test_f

        else:
            print('None')
            return 0, 0, 0, 0, 0, 0, 0, 0, 0

    # 全部
    elif session_select == 'all':
        df_all_pre = df_session
        df_flag_data = df_flag.query('1<= doc < 8')
        
        df_all = df_all_pre.drop('doc', axis=1)
        df_flag_pre = df_flag_data.drop('doc', axis=1)
        
        # データ数が(train_size + test_size)以上あるか
        if df_all['user'].count() >= (train_size + test_size):
            # 説明変数と目的変数に分割
            x, y = x_y_split(df_all)

            # その他のデータとテスト用(認証用)データに切り分け
            x_train_all, x_test_t, y_train_all, y_test_t = train_test_split(x, y, test_size=test_size, random_state=0,
                                                                            shuffle=True)
            # 学習用データとその他のデータ2に切り分け
            x_train, x_others, y_train, y_others = train_test_split(x_train_all, y_train_all, train_size=train_size,
                                                                    random_state=0, shuffle=True)
            # テストデータの個数をカウント➝外れ値はテストデータ数と同じ数だけ用意する
            # _outlinerの呼び出し
            fake_data_except_test_f, test_f = _outlier(df_flag_pre, user_n, test_size)

            # test_tとtest_fの結合
            x_test, y_test, x_test_f, y_test_f = _tf_concat(x_test_t, y_test_t, test_f)

            return x_train, y_train, x_test, y_test, x_test_t, y_test_t, x_test_f, y_test_f, test_f, \
                fake_data_except_test_f
        else:
            print('None')
            return 0, 0, 0, 0, 0, 0, 0, 0, 0

In [211]:
class OneClassOne(object):

    def __init__(self, df_flag, df_flag_user_extract, u_n, flag_n, session_select):
        flag_memori = ['0', 'a', 'b', 'c', 'd']
        print(
            f'\n-----------------------------------------------------------------\n{user_n} : {flag_memori[flag_n]}'
            f'\n-----------------------------------------------------------------')
        try:
            self.df_flag = df_flag
            self.df_flag_user_extract = df_flag_user_extract
            self.u_n = u_n
            self.flag_n = flag_n
            self.session_select = session_select

            self.x_train, self.y_train, self.x_test, self.y_test, self.x_test_t,\
                self.y_test_t, self.x_test_f, self.y_test_f, self.test_f, self.fake_data_except_test_f \
                = datasplit_session_test(self.df_flag, self.df_flag_user_extract, self.u_n, self.session_select, train_size=40)

            # 標準化
            # print(self.x_train.columns)
            ss = preprocessing.StandardScaler()
            ss.fit(self.x_train)
            self.x_train_ss = ss.transform(self.x_train)
            self.x_test_ss = ss.transform(self.x_test)
            self.x_test_t_ss = ss.transform(self.x_test_t)
            # print(self.x_test_t.columns)
            # print(self.x_test_t.shape)
            # print(self.x_test_f.columns)
            # print(self.x_test_f.shape)
            self.x_test_f_ss = ss.transform(self.x_test_f)

            self.columns = self.x_train.columns.values

        except AttributeError as ex:
            print(f"No data:{ex}")
            pass
        
        except ValueError as ex2:
            print(f'No data: {self.session_select} == {ex2}')
            pass

#     def registration_phase(self):
#         try:
#             if list(self.test_f['user']) != 0:
#                 print('\n外れ値として扱うuserのnumber\n', '\n')

#             # モデル
#             models = [LocalOutlierFactor(n_neighbors=1, novelty=True, contamination=0.1),
#                       IsolationForest(n_estimators=1, contamination='auto', behaviour='new', random_state=0),
#                       OneClassSVM(nu=0.1, kernel="rbf"),
#                       EllipticEnvelope(contamination=0.1, random_state=0)]
#             scores = {'LocalOutlierFactor': {}, 'IsolationForest': {}, 'OneClassSVM': {}, 'EllipticEnvelope': {}}
#             scores_test = {}

#             # 目的関数を出力結果にあわせて本人：1，他人:-1に変更する．
#             y_test_true = self.y_test.copy()
#             y_true = y_test_true.replace({self.u_n: 1, 0: -1})

#             # k分割交差検証 k=10
#             k = 10
#             kf = KFold(n_splits=k, shuffle=True, random_state=0)
#             for model in models:
#                 # columnsが消滅しているのでデータフレーム化してヘッダー追加
#                 x_train_ss_df = pd.DataFrame(self.x_train_ss, columns=self.columns)
#                 # print(len(self.y_train))
#                 count = 0
#                 for train_index, val_index in kf.split(x_train_ss_df, self.y_train):
#                     model.fit(x_train_ss_df.iloc[train_index])
#                     # 検証用データに偽物のデータを付与
#                     # self.df_flagではなくdatasplit_train_test_valで作成したどこにも属していないデータ？
#                     x_val, y_val_true, x_val_t, x_val_f = fake_val(self.df_flag, x_train_ss_df.iloc[val_index],
#                                                                    self.y_train.iloc[val_index], self.u_n,
#                                                                    self.x_train, self.columns,
#                                                                    self.fake_data_except_test_f)
#                     # 予測
#                     val_pred = model.predict(x_val)
#                     normal_result = model.predict(x_val_t)
#                     anomaly_result = model.predict(x_val_f)

#                     # print(y_val_true)
#                     # 評価
#                     far, frr, ber = far_frr_ber(normal_result, anomaly_result)

#                     scores[str(model).split('(')[0]][count] = {'Accuracy': accuracy_score(y_true=y_val_true,
#                                                                                           y_pred=val_pred),
#                                                                'Precision': precision_score(y_val_true, val_pred),
#                                                                'Recall': recall_score(y_val_true, val_pred),
#                                                                'F1': f1_score(y_val_true, val_pred),
#                                                                'AUC': roc_auc_score(y_val_true,
#                                                                                     model.decision_function(x_val)),
#                                                                'FAR': far, 'FRR': frr, 'BER': ber}
#                     count += 1

#                     # testデータにて汎化性能評価
#                     model.fit(x_train_ss_df)
#                     test_pred = model.predict(self.x_test_ss)
#                     test_normal_result = model.predict(self.x_test_t_ss)
#                     test_anomaly_result = model.predict(self.x_test_f_ss)

#                     t_far, t_frr, t_ber = far_frr_ber(test_normal_result, test_anomaly_result)

#                     scores_test[str(model).split('(')[0]] = {
#                         'Accuracy': accuracy_score(y_true=y_true, y_pred=test_pred),
#                         'Precision': precision_score(y_true, test_pred),
#                         'Recall': recall_score(y_true, test_pred),
#                         'F1': f1_score(y_true, test_pred),
#                         'AUC': roc_auc_score(y_true,
#                                              model.decision_function(self.x_test_ss)),
#                         'FAR': t_far, 'FRR': t_frr, 'BER': t_ber}

#             # 結果のまとめ
#             model_index = ['LocalOutlierFactor', 'IsolationForest', 'OneClassSVM', 'EllipticEnvelope']
#             result_index = ['Accuracy', 'Precision', 'Recall', 'F1', 'AUC', 'FAR', 'FRR', 'BER']
#             a = np.zeros((4, 8))
#             for i, m_i in enumerate(model_index):
#                 for j, df_i in enumerate(result_index):
#                     b = 0
#                     for m in range(k):
#                         b += scores[m_i][m][df_i]
#                     a[i][j] = b / k
#             a_df = pd.DataFrame(a, index=model_index, columns=result_index)
#             print('交差検証k=10の結果')
#             print(a_df)

#             s_test = pd.DataFrame(scores_test).T
#             print(f'認証用データ')
#             print(s_test[result_index])

#             # result_old.csvへ書き出し
#             def output_data(a2, model_index2, result_index2, text):
#                 # フォルダがなければ自動的に作成
#                 os.makedirs('result', exist_ok=True)
#                 # Columnの作成
#                 user = pd.Series([self.u_n] * 4, name='user')
#                 flag = pd.Series([self.flag_n] * 4, name='flag')
#                 performance = pd.Series([text] * 4, name='performance')
#                 model2 = pd.Series(model_index2, name='model')
#                 # valとtestで条件指定してresult作成
#                 if text == 'val':
#                     result = pd.DataFrame(a2, columns=result_index2)
#                 else:
#                     print('\ntestデータでの結果')
#                     result = pd.DataFrame(a2).T
#                     print(result)
#                     result = result.reset_index()
#                     result = result.drop('index', 1)
#                 # 全て結合
#                 all_result = pd.concat([user, flag, performance, model2, result], axis=1)
#                 # 書き出し
#                 all_result.to_csv(f'result/result_2020_10/result_{text}.csv', mode='a', header=False,
#                                   index=False)

#             # 交差検証の結果の書き出し
#             # output_data(a, model_index, result_index, 'val')
#             # テストデータの結果の書き出し
#             # output_data(scores_test, model_index, result_index, 'test')
#         except AttributeError as ex:
#             print(f"No train data:{ex}")
#             pass

#     def authentication_phase(self):
#         # TODO: あとで考える
#         try:
#             test = 0
#             print(f'{test} No data')
#         except AttributeError as ex:
#             print(f"No test data:{ex}")
#             pass

### ここからデータの検証

'first'で検証  
学習用データとテストデータはどちらもdocが１〜６（つまり同日採取のもの）

In [ ]:
# oneclassone_a = OneClassOne(a, a_user_extract, user_n, 1, session)
# oneclassone_a.registration_phase()
# # oneclassone_a.authentication_phase()
# oneclassone_b = OneClassOne(b, b_user_extract, user_n, 2, session)
# oneclassone_b.registration_phase()

#### 渡すデータの確認

In [91]:
user_n = 23
session = 'first'

In [105]:
c.head()

,user,doc,stroke_inter,stroke_duration,start_x,start_y,stop_x,stop_y,direct_ete_distance,mean_result_leng,...,ave_direction,length_trajectory,ratio_ete,ave_v,5points_m_acc,m_stroke_press,m_stroke_area_cover,finger_orien,cd_finger_orien,phone_orien
0,37,1,1.326,1.073,28.121,-37.394,32.052,-10.684,26.998,0.92509,...,1.3232,28.031,0.96315,26.1240,11611.000000,0.51,0.044444,0.0,0,1
1,37,1,2.934,0.704,25.602,-39.511,27.416,-24.594,15.027,0.68201,...,1.0391,16.212,0.92693,23.0280,0.074442,0.47,0.088889,0.0,0,1
2,37,1,0.686,0.432,27.416,-43.644,30.440,-21.671,22.180,0.63109,...,1.0845,26.002,0.85303,60.1890,-904.790000,0.49,0.044444,0.0,0,1
3,37,1,9.054,0.751,25.299,-44.551,28.222,-28.625,16.191,0.78558,...,1.1723,17.302,0.93580,23.0390,-377.810000,0.44,0.088889,0.0,0,1
4,37,1,11.804,1.734,25.501,-42.233,28.021,-27.013,15.427,0.77228,...,1.1556,16.826,0.91688,9.7034,1.205500,0.41,0.088889,0.0,0,1

In [106]:
c_user_extract.head()

,user,doc,stroke_inter,stroke_duration,start_x,start_y,stop_x,stop_y,direct_ete_distance,mean_result_leng,...,ave_direction,length_trajectory,ratio_ete,ave_v,5points_m_acc,m_stroke_press,m_stroke_area_cover,finger_orien,cd_finger_orien,phone_orien
5748,23,4,2.074,0.190,34.121,-46.767,34.121,-37.173,9.5931,0.62924,...,1.3897,9.8564,0.97329,51.876,-1419.90,0.07451,0.055556,0.0,0,1
5749,23,1,2.060,0.337,27.907,-44.259,28.997,-30.633,13.6700,0.84380,...,1.0878,13.9350,0.98096,41.351,14294.00,0.21176,0.088889,0.0,0,1
5750,23,1,0.955,0.420,26.490,-44.368,27.907,-29.324,15.1100,0.92650,...,1.3388,15.4640,0.97711,36.820,305.03,0.25098,0.122220,0.0,0,1
5751,23,1,9.884,0.389,27.689,-49.165,27.035,-40.989,8.2021,0.91962,...,1.5889,8.3294,0.98471,21.412,460.02,0.22353,0.100000,0.0,0,1
5752,23,1,0.565,0.140,26.708,-45.676,25.727,-29.870,15.8370,0.84246,...,1.4974,16.0020,0.98973,114.300,1861.70,0.20392,0.088889,0.0,0,1

In [ ]:
# インスタンスの生成

In [138]:
oneclassone_c = OneClassOne(c, c_user_extract, user_n, 3, session)
# oneclassone_c.registration_phase()

-----------------------------------------------------------------
23 : c
-----------------------------------------------------------------

#### インスタンス変数の確認

In [139]:
oneclassone_c.df_flag.head()

,user,doc,stroke_inter,stroke_duration,start_x,start_y,stop_x,stop_y,direct_ete_distance,mean_result_leng,...,ave_direction,length_trajectory,ratio_ete,ave_v,5points_m_acc,m_stroke_press,m_stroke_area_cover,finger_orien,cd_finger_orien,phone_orien
0,37,1,1.326,1.073,28.121,-37.394,32.052,-10.684,26.998,0.92509,...,1.3232,28.031,0.96315,26.1240,11611.000000,0.51,0.044444,0.0,0,1
1,37,1,2.934,0.704,25.602,-39.511,27.416,-24.594,15.027,0.68201,...,1.0391,16.212,0.92693,23.0280,0.074442,0.47,0.088889,0.0,0,1
2,37,1,0.686,0.432,27.416,-43.644,30.440,-21.671,22.180,0.63109,...,1.0845,26.002,0.85303,60.1890,-904.790000,0.49,0.044444,0.0,0,1
3,37,1,9.054,0.751,25.299,-44.551,28.222,-28.625,16.191,0.78558,...,1.1723,17.302,0.93580,23.0390,-377.810000,0.44,0.088889,0.0,0,1
4,37,1,11.804,1.734,25.501,-42.233,28.021,-27.013,15.427,0.77228,...,1.1556,16.826,0.91688,9.7034,1.205500,0.41,0.088889,0.0,0,1

In [140]:
oneclassone_c.df_flag_user_extract.head()

,user,doc,stroke_inter,stroke_duration,start_x,start_y,stop_x,stop_y,direct_ete_distance,mean_result_leng,...,ave_direction,length_trajectory,ratio_ete,ave_v,5points_m_acc,m_stroke_press,m_stroke_area_cover,finger_orien,cd_finger_orien,phone_orien
5748,23,4,2.074,0.190,34.121,-46.767,34.121,-37.173,9.5931,0.62924,...,1.3897,9.8564,0.97329,51.876,-1419.90,0.07451,0.055556,0.0,0,1
5749,23,1,2.060,0.337,27.907,-44.259,28.997,-30.633,13.6700,0.84380,...,1.0878,13.9350,0.98096,41.351,14294.00,0.21176,0.088889,0.0,0,1
5750,23,1,0.955,0.420,26.490,-44.368,27.907,-29.324,15.1100,0.92650,...,1.3388,15.4640,0.97711,36.820,305.03,0.25098,0.122220,0.0,0,1
5751,23,1,9.884,0.389,27.689,-49.165,27.035,-40.989,8.2021,0.91962,...,1.5889,8.3294,0.98471,21.412,460.02,0.22353,0.100000,0.0,0,1
5752,23,1,0.565,0.140,26.708,-45.676,25.727,-29.870,15.8370,0.84246,...,1.4974,16.0020,0.98973,114.300,1861.70,0.20392,0.088889,0.0,0,1

In [141]:
oneclassone_c.u_n

23

In [142]:
oneclassone_c.flag_n

3

In [143]:
oneclassone_c.session_select

'first'

#### ここまでは受け渡したものと同じ

→渡したものと同じ値であることが確認できる

#### ここからdatasplit_sessionにて処理済みの結果

In [144]:
# 指定のtrain_size分のデータが取得できている
oneclassone_c.x_train

,stroke_inter,stroke_duration,start_x,start_y,stop_x,stop_y,direct_ete_distance,mean_result_leng,direct_ete_line,20_pairwise_v,...,ave_direction,length_trajectory,ratio_ete,ave_v,5points_m_acc,m_stroke_press,m_stroke_area_cover,finger_orien,cd_finger_orien,phone_orien
5840,0.218,0.110,16.679,-42.515,18.096,-39.136,3.6645,0.87074,1.1737,11.65300,...,0.91708,3.6888,0.99342,33.5350,716.800,0.17647,0.100000,0.0,0,1
6077,8.860,0.585,23.329,-43.714,24.855,-41.207,2.9353,0.68240,1.0240,0.00000,...,0.66222,3.3186,0.88449,5.6728,-461.220,0.18431,0.066667,0.0,0,1
5991,4.499,0.503,23.656,-43.932,24.092,-34.993,8.9497,0.83902,1.5221,6.30560,...,1.44330,9.1897,0.97388,18.2700,-1219.100,0.16863,0.100000,0.0,0,1
5916,0.707,0.409,24.855,-45.458,25.618,-33.685,11.7980,0.92836,1.5061,16.35000,...,1.37800,12.0460,0.97939,29.4530,-57.149,0.16471,0.088889,0.0,0,1
5882,1.248,0.305,24.637,-42.951,27.253,-34.339,9.0007,0.88318,1.2759,12.07700,...,1.03580,9.3064,0.96715,30.5130,-230.920,0.19216,0.088889,0.0,0,1
6191,1.346,0.124,26.599,-45.022,27.362,-32.813,12.2330,0.82836,1.5084,70.16800,...,1.24530,12.4260,0.98450,100.2100,46.814,0.20000,0.088889,0.0,0,1
6187,12.145,0.358,25.618,-49.056,25.509,-42.188,6.8687,0.78921,1.5867,0.00000,...,1.23090,6.9474,0.98867,19.4060,-126.070,0.19608,0.088889,0.0,0,1
5782,0.655,0.212,23.983,-41.098,26.163,-27.580,13.6920,0.91858,1.4109,57.55400,...,1.28870,13.7580,0.99522,64.8960,122.210,0.17255,0.077778,0.0,0,1
6133,1.537,0.359,26.163,-45.349,27.253,-38.918,6.5235,0.84712,1.4029,2.86880,...,1.15700,6.6059,0.98752,18.4010,76.193,0.17255,0.133330,0.0,0,1
5823,3.054,0.275,24.746,-48.511,26.054,-39.790,8.8186,0.91654,1.4219,6.62300,...,1.31020,8.9532,0.98497,32.5570,-361.750,0.21176,0.077778,0.0,0,1
6146,8.554,0.359,24.201,-46.439,27.689,-36.628,10.4130,0.81402,1.2292,8.59520,...,1.14930,10.7520,0.96847,29.9490,-417.060,0.18431,0.088889,0.0,0,1
6035,1.392,0.355,23.111,-43.932,23.329,-40.117,3.8217,0.70771,1.5137,0.25955,...,1.27460,4.0161,0.95160,11.3130,-204.120,0.16078,0.088889,0.0,0,1
6117,13.531,0.456,28.125,-40.880,29.870,-31.941,9.1076,0.78178,1.3781,8.80310,...,1.27650,9.7450,0.93460,21.3710,-388.080,0.21961,0.088889,0.0,0,1
5748,2.074,0.190,34.121,-46.767,34.121,-37.173,9.5931,0.62924,1.5708,10.03300,...,1.38970,9.8564,0.97329,51.8760,-1419.900,0.07451,0.055556,0.0,0,1
6167,1.159,0.089,25.400,-46.548,25.509,-39.027,7.5227,0.79008,1.5563,30.01000,...,1.24220,7.5433,0.99727,84.7560,2307.100,0.16863,0.077778,0.0,0,1
5894,2.009,0.386,23.220,-47.530,23.874,-41.207,6.3565,0.60626,1.4677,5.45070,...,1.25830,7.1524,0.88872,18.5300,112.960,0.19608,0.088889,0.0,0,1
6052,0.749,0.401,24.419,-42.297,28.670,-27.798,15.1090,0.94548,1.2856,15.67000,...,1.24160,15.3650,0.98334,38.3170,-775.120,0.17647,0.111110,0.0,0,1
5836,0.916,0.185,26.163,-45.894,28.561,-35.429,10.7370,0.92523,1.3455,48.61600,...,1.23270,10.7700,0.99694,58.2140,-1108.600,0.20784,0.100000,0.0,0,1
5924,0.609,0.337,25.291,-46.658,28.125,-30.633,16.2740,0.92211,1.3957,11.19900,...,1.26830,16.6680,0.97632,49.4610,278.230,0.21176,0.111110,0.0,0,1
5835,0.634,0.208,26.054,-45.458,28.125,-36.301,9.3884,0.90587,1.3483,32.75700,...,1.27110,9.4854,0.98978,45.6030,35.476,0.20784,0.100000,0.0,0,1
5923,0.654,0.371,26.163,-49.601,27.253,-34.339,15.3010,0.88200,1.4995,9.99410,...,1.29750,15.6860,0.97542,42.2810,583.580,0.20392,0.100000,0.0,0,1
5881,10.464,0.376,21.803,-47.094,23.547,-41.861,5.5157,0.79509,1.2490,7.88480,...,1.09980,6.0142,0.91710,15.9950,-40.106,0.19216,0.088889,0.0,0,1
6014,0.776,0.506,24.637,-46.221,27.035,-31.941,14.4810,0.89382,1.4044,10.94700,...,1.25020,14.6830,0.98620,29.0180,-528.130,0.18431,0.088889,0.0,0,1
5992,2.544,0.446,23.329,-45.131,24.528,-39.354,5.9008,0.83572,1.3662,6.35900,...,1.25670,6.3907,0.92335,14.3290,206.360,0.15686,0.111110,0.0,0,1
5954,0.723,0.425,24.964,-40.335,27.253,-27.689,12.8510,0.70249,1.3917,7.43990,...,1.12100,13.8270,0.92942,32.5340,-216.340,0.24314,0.111110,0.0,0,1
5844,0.557,0.333,24.092,-44.913,25.727,-29.979,15.0240,0.88356,1.4617,21.26900,...,1.28620,15.3740,0.97721,46.1690,-23.528,0.20392,0.111110,0.0,0,1
5872,0.930,0.326,23.329,-46.112,24.855,-39.790,6.5043,0.91520,1.3339,9.65800,...,1.16810,6.6843,0.97308,20.5040,-258.470,0.22353,0.088889,0.0,0,1
5974,1.494,0.502,23.111,-46.221,24.855,-39.572,6.8747,0.84409,1.3143,6.41250,...,1.25930,7.2728,0.94526,14.4880,-489.220,0.18431,0.088889,0.0,0,1
5852,6.217,0.448,26.381,-34.121,28.125,-27.362,6.9802,0.84026,1.3182,6.06020,...,1.29240,7.2867,0.95795,16.2650,371.370,0.23529,0.111110,0.0,0,1
5900,7.383,0.322,25.182,-46.003,25.727,-40.335,5.6948,0.69852,1.4749,2.72530,...,1.08570,6.0871,0.93555,18.9040,-343.440,0.20000,0.088889,0.0,0,1
6097,1.046,0.127,24.092,-42.406,25.727,-31.614,10.9150,0.85218,1.4204,29.61400,...,1.18430,10.9340,0.99828,86.0960,-2136.100,0.20392,0.088889,0.0,0,1
5967,0.818,0.425,20.930,-46.330,21.803,-38.918,7.4640,0.82453,1.4537,0.60563,...,1.19300,7.5024,0.99488,17.6530,-303.170,0.21569,0.088889,0.0,0,1
6158,0.591,0.173,25.291,-47.639,25.073,-36.955,10.6850,0.86230,1.5912,46.95200,...,1.43330,10.7170,0.99708,61.9470,-1470.100,0.17647,0.088889,0.0,0,1
6181,0.685,0.186,25.291,-47.748,28.125,-31.287,16.7030,0.91146,1.4003,62.92300,...,1.31300,16.8360,0.99209,90.5180,1286.600,0.18039,0.088889,0.0,0,1
5982,0.947,0.358,23.111,-43.060,23.765,-37.827,5.2733,0.79915,1.4464,6.54470,...,1.36940,5.4861,0.96121,15.3240,-206.840,0.19216,0.088889,0.0,0,1
6110,0.927,0.355,25.836,-44.804,29.433,-31.287,13.9880,0.91178,1.3107,14.47800,...,1.16290,14.1610,0.98777,39.8910,-655.090,0.18431,0.066667,0.0,0,1
6073,5.861,0.356,23.547,-43.387,24.419,-38.809,4.6609,0.73876,1.3826,5.45060,...,1.22720,4.9260,0.94617,13.8370,-825.280,0.14118,0.077778,0.0,0,1
5803,0.907,0.342,25.727,-43.932,28.779,-31.505,12.7970,0.93085,1.3299,13.57400,...,1.21140,12.9280,0.98985,37.8010,220.420,0.18824,0.088889,0.0,0,1
6049,2.199,0.370,23.002,-44.259,24.092,-38.373,5.9868,0.84316,1.3877,1.40150,...,1.11310,6.0929,0.98258,16.4670,-624.570,0.17255,0.088889,0.0,0,1
5979,9.291,0.605,22.021,-47.421,24.419,-39.245,8.5205,0.93096,1.2855,10.62600,...,1.27440,8.8829,0.95920,14.6820,298.490,0.18039,0.077778,0.0,0,1

In [145]:
# 上に同じ
oneclassone_c.y_train

5840    23
6077    23
5991    23
5916    23
5882    23
6191    23
6187    23
5782    23
6133    23
5823    23
6146    23
6035    23
6117    23
5748    23
6167    23
5894    23
6052    23
5836    23
5924    23
5835    23
5923    23
5881    23
6014    23
5992    23
5954    23
5844    23
5872    23
5974    23
5852    23
5900    23
6097    23
5967    23
6158    23
6181    23
5982    23
6110    23
6073    23
5803    23
6049    23
5979    23
Name: user, dtype: int64

In [146]:
#  tとｆを合わせて２０データあれば良い
oneclassone_c.x_test

,stroke_inter,stroke_duration,start_x,start_y,stop_x,stop_y,direct_ete_distance,mean_result_leng,direct_ete_line,20_pairwise_v,...,ave_direction,length_trajectory,ratio_ete,ave_v,5points_m_acc,m_stroke_press,m_stroke_area_cover,finger_orien,cd_finger_orien,phone_orien
0,0.966,0.355,25.0730,-45.458,27.03500,-36.4100,9.2584,0.92748,1.35720,13.1880,...,1.24890,9.4862,0.97599,26.7220,-252.420,0.21961,0.111110,0.0000,0,1
1,0.755,0.200,26.0540,-47.748,28.45200,-39.2450,8.8348,0.92729,1.29590,38.1500,...,1.19490,8.9382,0.98843,44.6910,757.730,0.19608,0.066667,0.0000,0,1
2,2.998,0.288,24.2010,-45.022,24.52800,-40.4440,4.5902,0.76068,1.49950,5.2170,...,1.30420,4.9003,0.93673,17.0150,-53.995,0.16863,0.088889,0.0000,0,1
3,0.910,0.372,25.0730,-47.530,25.50900,-34.9930,12.5440,0.89390,1.53600,14.4140,...,1.36020,12.9030,0.97217,34.6860,-276.960,0.20000,0.088889,0.0000,0,1
4,0.699,0.343,26.0540,-44.477,28.56100,-29.7610,14.9290,0.84322,1.40200,9.5990,...,1.16290,15.5120,0.96238,45.2250,-474.500,0.21176,0.100000,0.0000,0,1
5,2.033,0.586,23.7650,-44.041,25.72700,-38.0450,6.3086,0.77797,1.25450,4.7975,...,1.00790,7.0889,0.88994,12.0970,120.890,0.15294,0.088889,0.0000,0,1
6,11.559,0.317,25.7270,-45.894,26.16300,-38.9180,6.9904,0.81753,1.50840,2.3125,...,1.19540,7.0491,0.99167,22.2370,62.386,0.19608,0.111110,0.0000,0,1
7,1.274,0.370,23.7650,-46.767,24.63700,-39.7900,7.0311,0.87986,1.44640,9.3132,...,1.24970,7.2062,0.97570,19.4760,-961.110,0.20000,0.133330,0.0000,0,1
8,1.869,1.606,24.5280,-41.970,27.14400,-33.2490,9.1050,0.48590,1.27930,1.9622,...,0.83751,19.3560,0.47041,12.0520,-47.148,0.20784,0.111110,0.0000,0,1
9,0.694,0.071,23.5470,-38.264,25.61800,-26.8170,11.6320,0.83039,1.39180,46.4650,...,1.09490,11.6390,0.99941,163.9300,-52025.000,0.18824,0.077778,0.0000,0,1
10,8.917,1.062,0.8721,-54.615,0.54506,-45.4580,9.1629,0.70150,1.60650,2.0444,...,1.34780,10.1170,0.90568,9.5265,0.000,0.32000,0.100000,0.0000,0,1
11,20.879,0.786,20.8210,-47.312,31.39600,-34.5570,16.5680,0.83685,0.87859,12.1200,...,0.85592,18.4650,0.89724,23.4930,101.150,0.27451,0.166670,0.0000,0,1
12,11.726,0.599,7.3039,-33.685,6.21370,-17.0060,16.7150,0.92737,1.63610,10.9010,...,1.57870,16.8310,0.99306,28.0990,1146.100,0.35000,0.088889,0.0000,0,1
13,10.352,1.027,5.0397,-40.821,4.03170,-33.0600,7.8263,0.73661,1.69990,3.4511,...,1.46390,8.5492,0.91544,8.3245,0.000,0.60000,0.044444,0.0000,0,1
14,1.158,0.675,4.1425,-22.675,3.48840,-18.3140,4.4093,0.74123,1.71970,3.5283,...,1.56910,4.8541,0.90837,7.1912,110.090,0.48000,0.133330,1.5708,0,2
15,5.957,0.747,18.6470,-44.349,23.68700,-19.5540,25.3020,0.90019,1.37030,13.2760,...,1.26170,26.2930,0.96232,35.1980,-969.650,0.49000,0.044444,0.0000,0,1
16,30.198,0.866,24.5940,-40.317,24.99700,-19.3520,20.9690,0.92439,1.55160,12.7990,...,1.47740,21.1670,0.99064,24.4420,-164.720,0.26000,0.044444,0.0000,0,1
17,5.150,4.537,17.6390,-41.729,24.19000,-24.0900,18.8160,0.76632,1.21520,0.0000,...,0.87196,21.1060,0.89152,4.6519,52.698,0.11765,0.100000,0.0000,0,1
18,0.911,0.201,12.9730,-45.676,11.22800,-38.7000,7.1915,0.78696,1.81580,2.7715,...,1.48510,7.2141,0.99687,35.8910,835.910,0.32000,0.088889,0.0000,0,1
19,19.540,5.445,13.3050,-46.163,31.14500,-6.0476,43.9040,0.77475,1.15230,0.0000,...,0.89714,49.0080,0.89585,9.0006,205.860,0.49000,0.044444,0.0000,0,1

In [147]:
oneclassone_c.y_test

0     23
1     23
2     23
3     23
4     23
5     23
6     23
7     23
8     23
9     23
10     0
11     0
12     0
13     0
14     0
15     0
16     0
17     0
18     0
19     0
Name: user, dtype: int64

In [148]:
oneclassone_c.x_test_t

,stroke_inter,stroke_duration,start_x,start_y,stop_x,stop_y,direct_ete_distance,mean_result_leng,direct_ete_line,20_pairwise_v,...,ave_direction,length_trajectory,ratio_ete,ave_v,5points_m_acc,m_stroke_press,m_stroke_area_cover,finger_orien,cd_finger_orien,phone_orien
5850,0.966,0.355,25.073,-45.458,27.035,-36.410,9.2584,0.92748,1.3572,13.1880,...,1.24890,9.4862,0.97599,26.722,-252.420,0.21961,0.111110,0.0,0,1
5808,0.755,0.200,26.054,-47.748,28.452,-39.245,8.8348,0.92729,1.2959,38.1500,...,1.19490,8.9382,0.98843,44.691,757.730,0.19608,0.066667,0.0,0,1
6026,2.998,0.288,24.201,-45.022,24.528,-40.444,4.5902,0.76068,1.4995,5.2170,...,1.30420,4.9003,0.93673,17.015,-53.995,0.16863,0.088889,0.0,0,1
5892,0.910,0.372,25.073,-47.530,25.509,-34.993,12.5440,0.89390,1.5360,14.4140,...,1.36020,12.9030,0.97217,34.686,-276.960,0.20000,0.088889,0.0,0,1
5927,0.699,0.343,26.054,-44.477,28.561,-29.761,14.9290,0.84322,1.4020,9.5990,...,1.16290,15.5120,0.96238,45.225,-474.500,0.21176,0.100000,0.0,0,1
6078,2.033,0.586,23.765,-44.041,25.727,-38.045,6.3086,0.77797,1.2545,4.7975,...,1.00790,7.0889,0.88994,12.097,120.890,0.15294,0.088889,0.0,0,1
5760,11.559,0.317,25.727,-45.894,26.163,-38.918,6.9904,0.81753,1.5084,2.3125,...,1.19540,7.0491,0.99167,22.237,62.386,0.19608,0.111110,0.0,0,1
5848,1.274,0.370,23.765,-46.767,24.637,-39.790,7.0311,0.87986,1.4464,9.3132,...,1.24970,7.2062,0.97570,19.476,-961.110,0.20000,0.133330,0.0,0,1
6112,1.869,1.606,24.528,-41.970,27.144,-33.249,9.1050,0.48590,1.2793,1.9622,...,0.83751,19.3560,0.47041,12.052,-47.148,0.20784,0.111110,0.0,0,1
6173,0.694,0.071,23.547,-38.264,25.618,-26.817,11.6320,0.83039,1.3918,46.4650,...,1.09490,11.6390,0.99941,163.930,-52025.000,0.18824,0.077778,0.0,0,1

In [149]:
oneclassone_c.y_test_t

5850    23
5808    23
6026    23
5892    23
5927    23
6078    23
5760    23
5848    23
6112    23
6173    23
Name: user, dtype: int64

In [150]:
oneclassone_c.x_test_f

,stroke_inter,stroke_duration,start_x,start_y,stop_x,stop_y,direct_ete_distance,mean_result_leng,direct_ete_line,20_pairwise_v,...,ave_direction,length_trajectory,ratio_ete,ave_v,5points_m_acc,m_stroke_press,m_stroke_area_cover,finger_orien,cd_finger_orien,phone_orien
0,8.917,1.062,0.8721,-54.615,0.54506,-45.4580,9.1629,0.70150,1.60650,2.0444,...,1.34780,10.1170,0.90568,9.5265,0.000,0.32000,0.100000,0.0000,0,1
1,20.879,0.786,20.8210,-47.312,31.39600,-34.5570,16.5680,0.83685,0.87859,12.1200,...,0.85592,18.4650,0.89724,23.4930,101.150,0.27451,0.166670,0.0000,0,1
2,11.726,0.599,7.3039,-33.685,6.21370,-17.0060,16.7150,0.92737,1.63610,10.9010,...,1.57870,16.8310,0.99306,28.0990,1146.100,0.35000,0.088889,0.0000,0,1
3,10.352,1.027,5.0397,-40.821,4.03170,-33.0600,7.8263,0.73661,1.69990,3.4511,...,1.46390,8.5492,0.91544,8.3245,0.000,0.60000,0.044444,0.0000,0,1
4,1.158,0.675,4.1425,-22.675,3.48840,-18.3140,4.4093,0.74123,1.71970,3.5283,...,1.56910,4.8541,0.90837,7.1912,110.090,0.48000,0.133330,1.5708,0,2
5,5.957,0.747,18.6470,-44.349,23.68700,-19.5540,25.3020,0.90019,1.37030,13.2760,...,1.26170,26.2930,0.96232,35.1980,-969.650,0.49000,0.044444,0.0000,0,1
6,30.198,0.866,24.5940,-40.317,24.99700,-19.3520,20.9690,0.92439,1.55160,12.7990,...,1.47740,21.1670,0.99064,24.4420,-164.720,0.26000,0.044444,0.0000,0,1
7,5.150,4.537,17.6390,-41.729,24.19000,-24.0900,18.8160,0.76632,1.21520,0.0000,...,0.87196,21.1060,0.89152,4.6519,52.698,0.11765,0.100000,0.0000,0,1
8,0.911,0.201,12.9730,-45.676,11.22800,-38.7000,7.1915,0.78696,1.81580,2.7715,...,1.48510,7.2141,0.99687,35.8910,835.910,0.32000,0.088889,0.0000,0,1
9,19.540,5.445,13.3050,-46.163,31.14500,-6.0476,43.9040,0.77475,1.15230,0.0000,...,0.89714,49.0080,0.89585,9.0006,205.860,0.49000,0.044444,0.0000,0,1

In [151]:
oneclassone_c.y_test_f

0    0
1    0
2    0
3    0
4    0
5    0
6    0
7    0
8    0
9    0
Name: user, dtype: int64

In [152]:
oneclassone_c.test_f

,user,stroke_inter,stroke_duration,start_x,start_y,stop_x,stop_y,direct_ete_distance,mean_result_leng,direct_ete_line,...,ave_direction,length_trajectory,ratio_ete,ave_v,5points_m_acc,m_stroke_press,m_stroke_area_cover,finger_orien,cd_finger_orien,phone_orien
0,25,8.917,1.062,0.8721,-54.615,0.54506,-45.4580,9.1629,0.70150,1.60650,...,1.34780,10.1170,0.90568,9.5265,0.000,0.32000,0.100000,0.0000,0,1
1,15,20.879,0.786,20.8210,-47.312,31.39600,-34.5570,16.5680,0.83685,0.87859,...,0.85592,18.4650,0.89724,23.4930,101.150,0.27451,0.166670,0.0000,0,1
2,39,11.726,0.599,7.3039,-33.685,6.21370,-17.0060,16.7150,0.92737,1.63610,...,1.57870,16.8310,0.99306,28.0990,1146.100,0.35000,0.088889,0.0000,0,1
3,21,10.352,1.027,5.0397,-40.821,4.03170,-33.0600,7.8263,0.73661,1.69990,...,1.46390,8.5492,0.91544,8.3245,0.000,0.60000,0.044444,0.0000,0,1
4,2,1.158,0.675,4.1425,-22.675,3.48840,-18.3140,4.4093,0.74123,1.71970,...,1.56910,4.8541,0.90837,7.1912,110.090,0.48000,0.133330,1.5708,0,2
5,19,5.957,0.747,18.6470,-44.349,23.68700,-19.5540,25.3020,0.90019,1.37030,...,1.26170,26.2930,0.96232,35.1980,-969.650,0.49000,0.044444,0.0000,0,1
6,5,30.198,0.866,24.5940,-40.317,24.99700,-19.3520,20.9690,0.92439,1.55160,...,1.47740,21.1670,0.99064,24.4420,-164.720,0.26000,0.044444,0.0000,0,1
7,14,5.150,4.537,17.6390,-41.729,24.19000,-24.0900,18.8160,0.76632,1.21520,...,0.87196,21.1060,0.89152,4.6519,52.698,0.11765,0.100000,0.0000,0,1
8,24,0.911,0.201,12.9730,-45.676,11.22800,-38.7000,7.1915,0.78696,1.81580,...,1.48510,7.2141,0.99687,35.8910,835.910,0.32000,0.088889,0.0000,0,1
9,16,19.540,5.445,13.3050,-46.163,31.14500,-6.0476,43.9040,0.77475,1.15230,...,0.89714,49.0080,0.89585,9.0006,205.860,0.49000,0.044444,0.0000,0,1

In [153]:
oneclassone_c.fake_data_except_test_f

,user,stroke_inter,stroke_duration,start_x,start_y,stop_x,stop_y,direct_ete_distance,mean_result_leng,direct_ete_line,...,ave_direction,length_trajectory,ratio_ete,ave_v,5points_m_acc,m_stroke_press,m_stroke_area_cover,finger_orien,cd_finger_orien,phone_orien
10,7,2.078,0.661,29.9790,-42.7330,28.8880,-35.9740,6.8461,0.82469,1.7307,...,1.64570,8.1622,0.83876,12.3480,256.200000,0.37000,0.155560,0.0000,0,1
11,36,2.843,2.056,29.6520,-43.0600,31.9410,-32.5950,10.7130,0.80008,1.3554,...,1.17830,11.9510,0.89638,5.8128,-283.900000,0.18824,0.088889,0.0000,0,1
12,34,0.668,0.409,15.0440,-43.8230,15.3710,-37.6090,6.2223,0.75092,1.5182,...,1.25000,6.2873,0.98967,15.3720,-263.320000,0.42000,0.155560,0.0000,0,1
13,38,3.691,0.877,18.8590,-45.2400,20.0580,-40.4440,4.9442,0.76293,1.3258,...,0.87586,5.2311,0.94515,5.9648,484.480000,0.45000,0.133330,0.0000,0,1
14,2,2.907,0.653,5.0146,-9.5931,5.0146,-6.6498,2.9433,0.65341,1.5708,...,1.23570,3.5282,0.83423,5.4031,-0.015402,0.55000,0.188890,1.5708,0,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9898,26,13.895,1.470,28.4520,-51.3450,28.4520,-35.3200,16.0250,0.87507,1.5708,...,1.45370,16.4710,0.97293,11.2050,343.100000,0.45000,0.111110,0.0000,0,1
9899,21,18.845,1.286,1.5119,-44.4500,1.9151,-30.9440,13.5120,0.86988,1.5410,...,1.46590,14.1120,0.95749,10.9740,-131.230000,0.63000,0.044444,0.0000,0,1
9900,39,4.578,0.522,18.8590,-41.8610,19.4040,-33.9030,7.9766,0.70304,1.5024,...,1.14540,8.3560,0.95459,16.0080,-883.490000,0.39000,0.111110,0.0000,0,1
9901,13,3.201,0.214,29.8350,-39.6120,30.2380,-33.8670,5.7594,0.91290,1.5007,...,1.38760,5.8850,0.97865,27.5000,135.230000,0.43000,0.044444,0.0000,0,1
9902,34,2.380,0.967,16.5700,-47.4210,22.0210,-32.1590,16.2060,0.93992,1.2278,...,1.25660,16.6080,0.97582,17.1740,-135.430000,0.56500,0.188890,0.0000,0,1

In [154]:
oneclassone_c.x_train_ss

array([[-0.78425553, -1.83437877, -3.24394642, ...,  0.        ,
         0.        ,  0.        ],
       [ 1.63219381,  1.97138631, -0.50503994, ...,  0.        ,
         0.        ,  0.        ],
       [ 0.41278446,  1.31439108, -0.37035988, ...,  0.        ,
         0.        ,  0.        ],
       ...,
       [-0.59159948,  0.02443702,  0.48261386, ...,  0.        ,
         0.        ,  0.        ],
       [-0.23033443,  0.24877685, -0.63972   , ...,  0.        ,
         0.        ,  0.        ],
       [ 1.7527087 ,  2.13162905, -1.04376019, ...,  0.        ,
         0.        ,  0.        ]])

In [155]:
oneclassone_c.x_test_ss

array([[-5.75102080e-01,  1.28594799e-01,  2.13253730e-01,
        -1.94266235e-01,  3.55717048e-01, -1.56992195e-01,
        -3.06730947e-02,  1.06918562e+00, -3.16746688e-01,
        -1.53979998e-01, -4.88987320e-01, -1.92179433e-01,
         1.51722032e-01, -1.29345262e-01, -1.59644295e-01,
        -2.54632299e-01, -2.13235024e-01, -1.35153140e-01,
        -6.62863053e-01, -6.83806021e-01,  1.99669888e-01,
        -3.94769184e-02,  2.69969186e-01, -3.59381497e-01,
        -6.33260806e-02,  1.14789577e+00,  1.39268007e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [-6.34101248e-01, -1.11328644e+00,  6.17293919e-01,
        -1.01913005e+00,  9.04612897e-01, -8.05432003e-01,
        -1.43853608e-01,  1.06697273e+00, -8.49546908e-01,
         1.26444289e+00,  6.77736367e-02, -8.43687836e-02,
         1.86320119e-01, -1.01302478e-01, -1.61097752e-01,
         3.14612565e-01,  8.15414207e-02,  2.03979462e-01,
         6.44589524e-02,  1.29307187e-01, -1.98086229e-01,
        -1.85705022e-01,  7.02740899e-01,  4.04559855e-01,
         1.30504258e+00,  3.00264339e-01, -1.74580661e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [-6.92051853e-03, -4.08218380e-01, -1.45893105e-01,
        -3.72179275e-02, -6.15406376e-01, -1.07967515e+00,
        -1.27795655e+00, -8.73501793e-01,  9.20079922e-01,
        -6.06918418e-01, -8.76631576e-01, -2.76300444e-01,
         1.71561232e-01,  2.47132219e-01, -1.61566885e-01,
        -5.01101321e-01, -9.81532186e-02,  7.29835021e-01,
         8.14674219e-01,  2.88796310e-01,  6.07001616e-01,
        -1.26317667e+00, -1.09583607e+00, -7.72068832e-01,
         2.05464249e-01, -6.88578959e-01, -1.76527959e-01,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [-5.90760627e-01,  2.64801128e-01,  2.13253730e-01,
        -9.40605899e-01, -2.35401558e-01,  1.67113346e-01,
         8.47197287e-01,  6.78085841e-01,  1.23732638e+00,
        -8.43146487e-02, -2.24576256e-01, -1.57391905e-01,
         2.03381831e-01, -2.08489240e-01, -1.62392275e-01,
        -4.48390494e-01, -1.54526830e+00, -1.81419615e+00,
        -1.35267245e+00, -3.91070482e-01,  1.01948944e+00,
         8.72260647e-01,  1.37076265e-01, -2.07967717e-02,
        -9.65684376e-02,  4.41476205e-01, -1.76527959e-01,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [-6.49759795e-01,  3.24491549e-02,  6.17293919e-01,
         1.59092457e-01,  9.46835654e-01,  1.36381073e+00,
         1.48443884e+00,  8.78256602e-02,  7.26407477e-02,
        -3.57918775e-01,  8.45985228e-02, -1.27613997e-01,
         1.56030947e-01,  4.52290223e-02, -1.62113815e-01,
        -5.01103826e-01, -2.68739729e+00, -2.55256656e+00,
        -1.98055961e+00,  1.29307187e-01, -4.33793558e-01,
         1.56844518e+00, -2.03505331e-01,  4.27262548e-01,
        -3.64159929e-01,  8.65111804e-01,  6.08111367e-01,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [-2.76750837e-01,  1.97939845e+00, -3.25466522e-01,
         3.16140765e-01, -1.50956042e-01, -5.30960127e-01,
        -8.18822002e-01, -6.72128500e-01, -1.20938262e+00,
        -6.30755787e-01, -8.59610726e-01, -3.28111657e-01,
         2.19235001e-01,  2.53072865e-01, -1.62886568e-01,
        -6.61743961e-01,  5.33348533e-01,  7.34453495e-01,
         5.19159367e-01,  8.28896308e-02, -1.57550093e+00,
        -6.79171506e-01, -2.72360041e+00, -9.81154678e-01,
         4.42366841e-01, -1.25378666e+00, -1.76527959e-01,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 2.38687985e+00, -1.75866407e-01,  4.82613856e-01,
        -3.51314543e-01,  1.79349879e-02, -7.30638417e-01,
        -6.36653745e-01, -2.11380813e-01,  9.97435908e-01,
        -7.71961654e-01, -7.52250596e-01, -2.33569733e-01,
         1.80093794e-01, -8.39707950e-02, -1.63677661e-01,
        -6.61743961e-01,  5.90551528e-01,  7.99730097e-01,
         6.65770281e-01,  1.29307187e-01, -1.94403302e-01,
        -6.89791722e-01,  8.15456361e-01, -5.50058606e-01,
         3.63116195e-01,  3.00264339e-01,  1.39268007e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [-4.88980072e-01,  2.48776854e-01, -3.25466522e-01,
        -6.65771360e-01, -5.73183618e-01, -9.30087980e-01,
        -6.25779225e-01,  5.14564670e-01,  4.58551510e-01,
        -3.74158870e-01, -6.92957569e-01, -2.83620809e-01,
         1.80946481e-01,  2.98365488e-02, -1.63100151e-01,
        -4.60730855e-01,  1.03095123e-01,  2.51920524e-01,
        -4.71806959e-02,  1.29307187e-01,  2.05562571e-01,
        -6.47871220e-01,  2.59880457e-01, -6.67440880e-01,
        -1.02333122e+00,  4.41476205e-01,  2.96181749e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [-3.22608010e-01,  1.01517782e+01, -1.12130419e-02,
         1.06212023e+00,  3.97939806e-01,  5.66012473e-01,
        -7.16596166e-02, -4.07381143e+00, -9.93828860e-01,
        -7.91866852e-01, -8.60394581e-01, -3.14734615e-01,
         2.05352677e-01,  2.53072865e-01, -1.62145691e-01,
        -4.82139853e-01, -9.88926940e-01, -9.06145595e-01,
        -1.84112893e+00, -3.63358476e+00, -2.83056880e+00,
         2.59417662e+00, -1.73185133e+01, -9.83067826e-01,
         2.14739328e-01,  7.23899938e-01,  1.39268007e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [-6.51157880e-01, -2.14685211e+00, -4.15253231e-01,
         2.39703084e+00, -1.93178800e-01,  2.03718173e+00,
         6.03522528e-01, -6.16028742e-02, -1.60144275e-02,
         1.73692852e+00,  2.58050063e+01,  9.36769343e+00,
        -3.82086465e+00, -7.85651787e+01,  3.17178281e+00,
         2.35054224e+01,  5.89151623e-01,  8.87253434e-01,
         9.17263289e-01,  2.44688851e-01, -9.34671632e-01,
         5.34975385e-01,  1.08472108e+00,  5.47393505e+00,
        -7.01954609e+01,  1.78406063e-02, -9.61167285e-01,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 1.64813197e+00,  5.79317566e+00, -9.75426534e+00,
        -3.49264090e+00, -9.90555189e+00, -2.22651014e+00,
        -5.61894757e-02, -1.56275983e+00,  1.85009009e+00,
        -7.87195978e-01, -8.71424539e-01, -3.59040424e-01,
         2.23412034e-01,  1.73428935e-01, -1.63128958e-01,
        -4.82936490e-01,  2.67018209e+00,  1.81485119e+00,
         2.80853298e+00,  6.56082363e+00,  9.28152851e-01,
         1.28845505e-01, -2.17602592e+00, -1.09043796e+00,
         2.78606917e-01,  4.76428844e+00,  6.08111367e-01,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 4.99290945e+00,  3.58182585e+00, -1.53799896e+00,
        -8.62081745e-01,  2.04501472e+00,  2.66838127e-01,
         1.92235872e+00,  1.36354993e-02, -4.47667349e+00,
        -2.14667269e-01, -6.57936051e-01, -2.83896112e-01,
         2.15781616e-01,  2.69924291e-01, -1.62196692e-01,
        -3.87505368e-01, -1.61936670e+00, -1.40721751e+00,
        -1.95155338e+00, -2.67063351e+00, -2.69496343e+00,
         2.35642254e+00, -2.46964274e+00, -4.96660513e-01,
         4.15626657e-01,  3.12558237e+00,  5.31622980e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 2.43357587e+00,  2.08355623e+00, -7.10522795e+00,
         4.04639827e+00, -7.70972059e+00,  4.28121805e+00,
         1.96163525e+00,  1.06790447e+00,  2.10736393e+00,
        -2.83934855e-01, -3.82579013e-01, -2.27788359e-01,
         2.00171178e-01,  2.53072865e-01, -1.59996801e-01,
        -5.81421388e-01,  2.09624537e+00,  1.11529254e+00,
         1.55212463e+00,  4.11499520e+00,  2.62892855e+00,
         1.92040662e+00,  8.63812685e-01, -3.00839161e-01,
         1.83113607e+00,  5.84499150e+00, -1.76527959e-01,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 2.04938224e+00,  5.51275087e+00, -8.03777412e+00,
         1.47599294e+00, -8.55495047e+00,  6.09241793e-01,
        -4.13311935e-01, -1.15384044e+00,  2.66189336e+00,
        -7.07262660e-01, -9.66455751e-01, -3.67674122e-01,
         2.01627000e-01,  1.80146477e-01, -1.61436213e-01,
        -5.51960844e-01,  1.55945440e+00,  1.16061148e+00,
         1.30476858e+00,  1.55540730e+00,  1.78332850e+00,
        -2.89505629e-01, -1.83648798e+00, -1.14154027e+00,
         2.78606917e-01,  1.48508503e+01, -3.31515588e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [-5.21415633e-01,  2.69247864e+00, -8.40729997e+00,
         8.01222824e+00, -8.76540574e+00,  3.98204370e+00,
        -1.32629072e+00, -1.10003219e+00,  2.83398870e+00,
        -7.02875902e-01, -9.83613776e-01, -3.72972585e-01,
         2.22904969e-01,  3.21020940e-01, -1.63080923e-01,
        -6.39720199e-01,  1.88835955e+00,  1.63112049e+00,
         2.32699783e+00,  3.59927879e+00,  2.55821635e+00,
        -1.27550466e+00, -2.08244425e+00, -1.18972185e+00,
         4.27736953e-01,  1.05280381e+01,  2.96181749e+00,
         1.57080000e+00,  0.00000000e+00,  1.00000000e+00],
       [ 8.20465919e-01,  3.26935250e+00, -2.43339485e+00,
         2.05198382e-01, -9.41180129e-01,  3.69842276e+00,
         4.25597204e+00,  7.51344258e-01, -2.02885630e-01,
        -1.48979549e-01, -2.03972069e-01,  2.09204020e-01,
        -1.57519370e-01, -2.28411585e-01, -7.80616481e-03,
        -3.92515665e-01, -1.76394304e+00, -6.86377782e-01,
         9.17263289e-01,  4.23522293e+00,  2.93952820e-01,
         4.44524297e+00, -2.05592655e-01,  9.70603878e-04,
        -1.03489966e+00,  1.08882724e+01, -3.31515588e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 7.59865944e+00,  4.22279681e+00,  1.59700900e-02,
         1.65753502e+00, -4.33732309e-01,  3.74462553e+00,
         3.09824975e+00,  1.03319699e+00,  1.37291665e+00,
        -1.76084257e-01, -5.55363035e-01, -2.57561754e-01,
         1.81293241e-01,  3.52087304e-03, -1.62471947e-01,
        -4.61372173e-01,  2.45306112e-01,  4.22381248e-01,
         1.39061500e-01, -9.19271680e-01,  1.88276753e+00,
         3.07742315e+00,  7.79623976e-01, -4.56314342e-01,
         5.54740300e-02,  2.60288232e+00, -3.31515588e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 5.94815072e-01,  3.36353518e+01, -2.84855541e+00,
         1.14892904e+00, -7.46335661e-01,  2.66091907e+00,
         2.52299563e+00, -8.07813802e-01, -1.55096579e+00,
        -9.03365505e-01, -1.05308572e+00, -3.95113755e-01,
         2.20072909e-01,  2.53072865e-01, -1.63117469e-01,
        -6.41704026e-01, -5.47015704e-01, -3.80485183e-01,
         1.03137032e+00,  1.04397228e+00, -2.57681513e+00,
         3.06114594e+00, -2.66863423e+00, -1.29767868e+00,
         3.49992644e-01, -2.52505369e+00,  6.08111367e-01,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [-5.90481010e-01, -1.10527430e+00, -4.77032047e+00,
        -2.72790389e-01, -5.76735753e+00, -6.80776026e-01,
        -5.82922392e-01, -5.67423704e-01,  3.66925952e+00,
        -7.45879766e-01,  9.55724917e-02, -7.34017760e-02,
         1.09724321e-01,  1.51948257e+00, -1.53499300e-01,
         7.05440763e-01,  1.52597738e+00,  1.13147965e+00,
         1.12680029e+00,  1.62234879e+00,  1.93948461e+00,
        -6.45763187e-01,  9.96357719e-01,  3.04330869e-02,
         1.41094672e+00,  4.76428844e+00, -1.76527959e-01,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 4.61850241e+00,  4.09103722e+01, -4.63358108e+00,
        -4.48209026e-01,  1.94778616e+00,  6.78769522e+00,
         9.22618900e+00, -7.09631218e-01, -2.09767271e+00,
        -9.03365505e-01, -9.66455751e-01, -3.66825645e-01,
         2.13449799e-01,  2.53072865e-01, -1.62347547e-01,
        -6.61743961e-01,  4.51824913e+00, -1.32512576e+00,
        -3.98267048e-01,  1.08471323e+01, -2.39134292e+00,
         1.05065046e+01, -2.51799906e+00, -1.11279628e+00,
         5.57468841e-01,  1.08882724e+01, -3.31515588e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00]])

In [156]:
oneclassone_c.x_test_t_ss

array([[-5.75102080e-01,  1.28594799e-01,  2.13253730e-01,
        -1.94266235e-01,  3.55717048e-01, -1.56992195e-01,
        -3.06730947e-02,  1.06918562e+00, -3.16746688e-01,
        -1.53979998e-01, -4.88987320e-01, -1.92179433e-01,
         1.51722032e-01, -1.29345262e-01, -1.59644295e-01,
        -2.54632299e-01, -2.13235024e-01, -1.35153140e-01,
        -6.62863053e-01, -6.83806021e-01,  1.99669888e-01,
        -3.94769184e-02,  2.69969186e-01, -3.59381497e-01,
        -6.33260806e-02,  1.14789577e+00,  1.39268007e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [-6.34101248e-01, -1.11328644e+00,  6.17293919e-01,
        -1.01913005e+00,  9.04612897e-01, -8.05432003e-01,
        -1.43853608e-01,  1.06697273e+00, -8.49546908e-01,
         1.26444289e+00,  6.77736367e-02, -8.43687836e-02,
         1.86320119e-01, -1.01302478e-01, -1.61097752e-01,
         3.14612565e-01,  8.15414207e-02,  2.03979462e-01,
         6.44589524e-02,  1.29307187e-01, -1.98086229e-01,
        -1.85705022e-01,  7.02740899e-01,  4.04559855e-01,
         1.30504258e+00,  3.00264339e-01, -1.74580661e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [-6.92051853e-03, -4.08218380e-01, -1.45893105e-01,
        -3.72179275e-02, -6.15406376e-01, -1.07967515e+00,
        -1.27795655e+00, -8.73501793e-01,  9.20079922e-01,
        -6.06918418e-01, -8.76631576e-01, -2.76300444e-01,
         1.71561232e-01,  2.47132219e-01, -1.61566885e-01,
        -5.01101321e-01, -9.81532186e-02,  7.29835021e-01,
         8.14674219e-01,  2.88796310e-01,  6.07001616e-01,
        -1.26317667e+00, -1.09583607e+00, -7.72068832e-01,
         2.05464249e-01, -6.88578959e-01, -1.76527959e-01,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [-5.90760627e-01,  2.64801128e-01,  2.13253730e-01,
        -9.40605899e-01, -2.35401558e-01,  1.67113346e-01,
         8.47197287e-01,  6.78085841e-01,  1.23732638e+00,
        -8.43146487e-02, -2.24576256e-01, -1.57391905e-01,
         2.03381831e-01, -2.08489240e-01, -1.62392275e-01,
        -4.48390494e-01, -1.54526830e+00, -1.81419615e+00,
        -1.35267245e+00, -3.91070482e-01,  1.01948944e+00,
         8.72260647e-01,  1.37076265e-01, -2.07967717e-02,
        -9.65684376e-02,  4.41476205e-01, -1.76527959e-01,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [-6.49759795e-01,  3.24491549e-02,  6.17293919e-01,
         1.59092457e-01,  9.46835654e-01,  1.36381073e+00,
         1.48443884e+00,  8.78256602e-02,  7.26407477e-02,
        -3.57918775e-01,  8.45985228e-02, -1.27613997e-01,
         1.56030947e-01,  4.52290223e-02, -1.62113815e-01,
        -5.01103826e-01, -2.68739729e+00, -2.55256656e+00,
        -1.98055961e+00,  1.29307187e-01, -4.33793558e-01,
         1.56844518e+00, -2.03505331e-01,  4.27262548e-01,
        -3.64159929e-01,  8.65111804e-01,  6.08111367e-01,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [-2.76750837e-01,  1.97939845e+00, -3.25466522e-01,
         3.16140765e-01, -1.50956042e-01, -5.30960127e-01,
        -8.18822002e-01, -6.72128500e-01, -1.20938262e+00,
        -6.30755787e-01, -8.59610726e-01, -3.28111657e-01,
         2.19235001e-01,  2.53072865e-01, -1.62886568e-01,
        -6.61743961e-01,  5.33348533e-01,  7.34453495e-01,
         5.19159367e-01,  8.28896308e-02, -1.57550093e+00,
        -6.79171506e-01, -2.72360041e+00, -9.81154678e-01,
         4.42366841e-01, -1.25378666e+00, -1.76527959e-01,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 2.38687985e+00, -1.75866407e-01,  4.82613856e-01,
        -3.51314543e-01,  1.79349879e-02, -7.30638417e-01,
        -6.36653745e-01, -2.11380813e-01,  9.97435908e-01,
        -7.71961654e-01, -7.52250596e-01, -2.33569733e-01,
         1.80093794e-01, -8.39707950e-02, -1.63677661e-01,
        -6.61743961e-01,  5.90551528e-01,  7.99730097e-01,
         6.65770281e-01,  1.29307187e-01, -1.94403302e-01,
        -6.89791722e-01,  8.15456361e-01, -5.50058606e-01,
         3.63116195e-01,  3.00264339e-01,  1.39268007e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [-4.88980072e-01,  2.48776854e-01, -3.25466522e-01,
        -6.65771360e-01, -5.73183618e-01, -9.30087980e-01,
        -6.25779225e-01,  5.14564670e-01,  4.58551510e-01,
        -3.74158870e-01, -6.92957569e-01, -2.83620809e-01,
         1.80946481e-01,  2.98365488e-02, -1.63100151e-01,
        -4.60730855e-01,  1.03095123e-01,  2.51920524e-01,
        -4.71806959e-02,  1.29307187e-01,  2.05562571e-01,
        -6.47871220e-01,  2.59880457e-01, -6.67440880e-01,
        -1.02333122e+00,  4.41476205e-01,  2.96181749e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [-3.22608010e-01,  1.01517782e+01, -1.12130419e-02,
         1.06212023e+00,  3.97939806e-01,  5.66012473e-01,
        -7.16596166e-02, -4.07381143e+00, -9.93828860e-01,
        -7.91866852e-01, -8.60394581e-01, -3.14734615e-01,
         2.05352677e-01,  2.53072865e-01, -1.62145691e-01,
        -4.82139853e-01, -9.88926940e-01, -9.06145595e-01,
        -1.84112893e+00, -3.63358476e+00, -2.83056880e+00,
         2.59417662e+00, -1.73185133e+01, -9.83067826e-01,
         2.14739328e-01,  7.23899938e-01,  1.39268007e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [-6.51157880e-01, -2.14685211e+00, -4.15253231e-01,
         2.39703084e+00, -1.93178800e-01,  2.03718173e+00,
         6.03522528e-01, -6.16028742e-02, -1.60144275e-02,
         1.73692852e+00,  2.58050063e+01,  9.36769343e+00,
        -3.82086465e+00, -7.85651787e+01,  3.17178281e+00,
         2.35054224e+01,  5.89151623e-01,  8.87253434e-01,
         9.17263289e-01,  2.44688851e-01, -9.34671632e-01,
         5.34975385e-01,  1.08472108e+00,  5.47393505e+00,
        -7.01954609e+01,  1.78406063e-02, -9.61167285e-01,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00]])

In [157]:
oneclassone_c.x_test_f_ss

array([[ 1.64813197e+00,  5.79317566e+00, -9.75426534e+00,
        -3.49264090e+00, -9.90555189e+00, -2.22651014e+00,
        -5.61894757e-02, -1.56275983e+00,  1.85009009e+00,
        -7.87195978e-01, -8.71424539e-01, -3.59040424e-01,
         2.23412034e-01,  1.73428935e-01, -1.63128958e-01,
        -4.82936490e-01,  2.67018209e+00,  1.81485119e+00,
         2.80853298e+00,  6.56082363e+00,  9.28152851e-01,
         1.28845505e-01, -2.17602592e+00, -1.09043796e+00,
         2.78606917e-01,  4.76428844e+00,  6.08111367e-01,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 4.99290945e+00,  3.58182585e+00, -1.53799896e+00,
        -8.62081745e-01,  2.04501472e+00,  2.66838127e-01,
         1.92235872e+00,  1.36354993e-02, -4.47667349e+00,
        -2.14667269e-01, -6.57936051e-01, -2.83896112e-01,
         2.15781616e-01,  2.69924291e-01, -1.62196692e-01,
        -3.87505368e-01, -1.61936670e+00, -1.40721751e+00,
        -1.95155338e+00, -2.67063351e+00, -2.69496343e+00,
         2.35642254e+00, -2.46964274e+00, -4.96660513e-01,
         4.15626657e-01,  3.12558237e+00,  5.31622980e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 2.43357587e+00,  2.08355623e+00, -7.10522795e+00,
         4.04639827e+00, -7.70972059e+00,  4.28121805e+00,
         1.96163525e+00,  1.06790447e+00,  2.10736393e+00,
        -2.83934855e-01, -3.82579013e-01, -2.27788359e-01,
         2.00171178e-01,  2.53072865e-01, -1.59996801e-01,
        -5.81421388e-01,  2.09624537e+00,  1.11529254e+00,
         1.55212463e+00,  4.11499520e+00,  2.62892855e+00,
         1.92040662e+00,  8.63812685e-01, -3.00839161e-01,
         1.83113607e+00,  5.84499150e+00, -1.76527959e-01,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 2.04938224e+00,  5.51275087e+00, -8.03777412e+00,
         1.47599294e+00, -8.55495047e+00,  6.09241793e-01,
        -4.13311935e-01, -1.15384044e+00,  2.66189336e+00,
        -7.07262660e-01, -9.66455751e-01, -3.67674122e-01,
         2.01627000e-01,  1.80146477e-01, -1.61436213e-01,
        -5.51960844e-01,  1.55945440e+00,  1.16061148e+00,
         1.30476858e+00,  1.55540730e+00,  1.78332850e+00,
        -2.89505629e-01, -1.83648798e+00, -1.14154027e+00,
         2.78606917e-01,  1.48508503e+01, -3.31515588e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [-5.21415633e-01,  2.69247864e+00, -8.40729997e+00,
         8.01222824e+00, -8.76540574e+00,  3.98204370e+00,
        -1.32629072e+00, -1.10003219e+00,  2.83398870e+00,
        -7.02875902e-01, -9.83613776e-01, -3.72972585e-01,
         2.22904969e-01,  3.21020940e-01, -1.63080923e-01,
        -6.39720199e-01,  1.88835955e+00,  1.63112049e+00,
         2.32699783e+00,  3.59927879e+00,  2.55821635e+00,
        -1.27550466e+00, -2.08244425e+00, -1.18972185e+00,
         4.27736953e-01,  1.05280381e+01,  2.96181749e+00,
         1.57080000e+00,  0.00000000e+00,  1.00000000e+00],
       [ 8.20465919e-01,  3.26935250e+00, -2.43339485e+00,
         2.05198382e-01, -9.41180129e-01,  3.69842276e+00,
         4.25597204e+00,  7.51344258e-01, -2.02885630e-01,
        -1.48979549e-01, -2.03972069e-01,  2.09204020e-01,
        -1.57519370e-01, -2.28411585e-01, -7.80616481e-03,
        -3.92515665e-01, -1.76394304e+00, -6.86377782e-01,
         9.17263289e-01,  4.23522293e+00,  2.93952820e-01,
         4.44524297e+00, -2.05592655e-01,  9.70603878e-04,
        -1.03489966e+00,  1.08882724e+01, -3.31515588e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 7.59865944e+00,  4.22279681e+00,  1.59700900e-02,
         1.65753502e+00, -4.33732309e-01,  3.74462553e+00,
         3.09824975e+00,  1.03319699e+00,  1.37291665e+00,
        -1.76084257e-01, -5.55363035e-01, -2.57561754e-01,
         1.81293241e-01,  3.52087304e-03, -1.62471947e-01,
        -4.61372173e-01,  2.45306112e-01,  4.22381248e-01,
         1.39061500e-01, -9.19271680e-01,  1.88276753e+00,
         3.07742315e+00,  7.79623976e-01, -4.56314342e-01,
         5.54740300e-02,  2.60288232e+00, -3.31515588e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 5.94815072e-01,  3.36353518e+01, -2.84855541e+00,
         1.14892904e+00, -7.46335661e-01,  2.66091907e+00,
         2.52299563e+00, -8.07813802e-01, -1.55096579e+00,
        -9.03365505e-01, -1.05308572e+00, -3.95113755e-01,
         2.20072909e-01,  2.53072865e-01, -1.63117469e-01,
        -6.41704026e-01, -5.47015704e-01, -3.80485183e-01,
         1.03137032e+00,  1.04397228e+00, -2.57681513e+00,
         3.06114594e+00, -2.66863423e+00, -1.29767868e+00,
         3.49992644e-01, -2.52505369e+00,  6.08111367e-01,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [-5.90481010e-01, -1.10527430e+00, -4.77032047e+00,
        -2.72790389e-01, -5.76735753e+00, -6.80776026e-01,
        -5.82922392e-01, -5.67423704e-01,  3.66925952e+00,
        -7.45879766e-01,  9.55724917e-02, -7.34017760e-02,
         1.09724321e-01,  1.51948257e+00, -1.53499300e-01,
         7.05440763e-01,  1.52597738e+00,  1.13147965e+00,
         1.12680029e+00,  1.62234879e+00,  1.93948461e+00,
        -6.45763187e-01,  9.96357719e-01,  3.04330869e-02,
         1.41094672e+00,  4.76428844e+00, -1.76527959e-01,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 4.61850241e+00,  4.09103722e+01, -4.63358108e+00,
        -4.48209026e-01,  1.94778616e+00,  6.78769522e+00,
         9.22618900e+00, -7.09631218e-01, -2.09767271e+00,
        -9.03365505e-01, -9.66455751e-01, -3.66825645e-01,
         2.13449799e-01,  2.53072865e-01, -1.62347547e-01,
        -6.61743961e-01,  4.51824913e+00, -1.32512576e+00,
        -3.98267048e-01,  1.08471323e+01, -2.39134292e+00,
         1.05065046e+01, -2.51799906e+00, -1.11279628e+00,
         5.57468841e-01,  1.08882724e+01, -3.31515588e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00]])

In [158]:
oneclassone_c.columns

array(['stroke_inter', 'stroke_duration', 'start_x', 'start_y', 'stop_x',
       'stop_y', 'direct_ete_distance', 'mean_result_leng',
       'direct_ete_line', '20_pairwise_v', '50_pairwise_v',
       '80_pairwise_v', '20_pairwise_acc', '50_pairwise_acc',
       '80_pairwise_acc', '3ots_m_v', 'ete_larg_deviation', '20_ete_line',
       '50_ete_line', '80_ete_line', 'ave_direction', 'length_trajectory',
       'ratio_ete', 'ave_v', '5points_m_acc', 'm_stroke_press',
       'm_stroke_area_cover', 'finger_orien', 'cd_finger_orien',
       'phone_orien'], dtype=object)

In [ ]:
# oneclassone_d = OneClassOne(d, d_user_extract, user_n, 4, session)
# oneclassone_d.registration_phase()

In [ ]:
# datasplit_sessionの中を検証していく

In [212]:
oneclassone_c_test = OneClassOne(c, c_user_extract, user_n, 3, 'latter')

-----------------------------------------------------------------
23 : c
-----------------------------------------------------------------
df_flag_user_extractに含まれるdocの値
[4 1 3 2]
session_select: latter
None
No data: latter == not enough values to unpack (expected 10, got 9)

In [213]:
oneclassone_c_test = OneClassOne(c, c_user_extract, user_n, 3, 'first')

-----------------------------------------------------------------
23 : c
-----------------------------------------------------------------
df_flag_user_extractに含まれるdocの値
[4 1 3 2]
session_select: first
df_first_preに含まれるdocの値
[4 1 3 2]
df_flag_dataに含まれるdocの値
[1 3 2 5 4]

In [238]:
x_train, y_train, x_test, y_test, x_test_t, y_test_t, x_test_f, y_test_f, test_f, fake_data_except_test_f = \
datasplit_session_test(oneclassone_c_test.df_flag, oneclassone_c_test.df_flag_user_extract, \
                       oneclassone_c_test.u_n, oneclassone_c_test.session_select, train_size=40, test_size=10)

df_flag_user_extractに含まれるdocの値:
[4 1 3 2]
session_select: first
df_first_preに含まれるdocの値:
[4 1 3 2]
df_flag_dataに含まれるdocの値:
[1 3 2 5 4]
colunmsの数を確認する(df_first_pre): (456, 32)
colunmsの数を確認する(df_first): (456, 31)
df_first:      user  stroke_inter  stroke_duration  start_x  start_y  stop_x  stop_y  \
5748    23         2.074            0.190   34.121  -46.767  34.121 -37.173
5749    23         2.060            0.337   27.907  -44.259  28.997 -30.633
5750    23         0.955            0.420   26.490  -44.368  27.907 -29.324
5751    23         9.884            0.389   27.689  -49.165  27.035 -40.989
5752    23         0.565            0.140   26.708  -45.676  25.727 -29.870

      direct_ete_distance  mean_result_leng  direct_ete_line  ...  \
5748               9.5931           0.62924           1.5708  ...
5749              13.6700           0.84380           1.4910  ...
5750              15.1100           0.92650           1.4769  ...
5751               8.2021           0.91962           1.6506  ...
5752              15.8370           0.84246           1.6328  ...

      ave_direction  length_trajectory  ratio_ete    ave_v  5points_m_acc  \
5748         1.3897             9.8564    0.97329   51.876       -1419.90
5749         1.0878            13.9350    0.98096   41.351       14294.00
5750         1.3388            15.4640    0.97711   36.820         305.03
5751         1.5889             8.3294    0.98471   21.412         460.02
5752         1.4974            16.0020    0.98973  114.300        1861.70

      m_stroke_press  m_stroke_area_cover  finger_orien  cd_finger_orien  \
5748         0.07451             0.055556           0.0                0
5749         0.21176             0.088889           0.0                0
5750         0.25098             0.122220           0.0                0
5751         0.22353             0.100000           0.0                0
5752         0.20392             0.088889           0.0                0

      phone_orien
5748            1
5749            1
5750            1
5751            1
5752            1

[5 rows x 31 columns]
x:       stroke_inter  stroke_duration
5748         2.074            0.190
5749         2.060            0.337
5750         0.955            0.420
y: 5748    23
5749    23
5750    23
5751    23
5752    23
        ..
6199    23
6200    23
6201    23
6202    23
6203    23
Name: user, Length: 456, dtype: int64
x_shape: (456, 30)
x_train_all:
       stroke_inter  stroke_duration
5994        10.782            0.354
6132         2.920            0.249
6087         1.609            0.461
y_train_all:
 5994    23
6132    23
6087    23
6129    23
5826    23
        ..
6071    23
5940    23
5865    23
5795    23
5920    23
Name: user, Length: 446, dtype: int64
x_train_all_shape:
 (446, 30)
y_train_all_len:
 446
x_test_t:
       stroke_inter  stroke_duration
5850         0.966            0.355
5808         0.755            0.200
6026         2.998            0.288
y_test_t:
 5850    23
5808    23
6026    23
5892    23
5927    23
6078    23
5760    23
5848    23
6112    23
6173    23
Name: user, dtype: int64
x_test_t_shape:
 (10, 30)
y_test_t_len:
 10
x_train:
       stroke_inter  stroke_duration
5840         0.218            0.110
6077         8.860            0.585
5991         4.499            0.503
y_train:
 5840    23
6077    23
5991    23
5916    23
5882    23
6191    23
6187    23
5782    23
6133    23
5823    23
6146    23
6035    23
6117    23
5748    23
6167    23
5894    23
6052    23
5836    23
5924    23
5835    23
5923    23
5881    23
6014    23
5992    23
5954    23
5844    23
5872    23
5974    23
5852    23
5900    23
6097    23
5967    23
6158    23
6181    23
5982    23
6110    23
6073    23
5803    23
6049    23
5979    23
Name: user, dtype: int64
x_train_shape:
 (40, 30)
y_train_len:
 40
x_others:
       stroke_inter  stroke_duration
6107         0.902            0.487
5863         2.498            0.421
6093        21.626            1.311
y_others:
 6107    23
5863    23
6093    23
5925    23
5837    23
        ..
5938    23
6013    23
6101    23
5779    23
5895    23
Name: user, Length: 406, dtype: int64
x_others_shape:
 (406, 30)
y_others_len:
 406
fake_data_except_test_f:
    user  stroke_inter
10     7         2.078
11    36         2.843
12    34         0.668
test_f:
   user  stroke_inter
0    25         8.917
1    15        20.879
2    39        11.726
x_test:
    stroke_inter  stroke_duration
0         0.966            0.355
1         0.755            0.200
2         2.998            0.288
y_test:
 0     23
1     23
2     23
3     23
4     23
5     23
6     23
7     23
8     23
9     23
10     0
11     0
12     0
13     0
14     0
15     0
16     0
17     0
18     0
19     0
Name: user, dtype: int64
x_test_shape:
 (20, 30)
y_test_len:
 20
x_test_f:
    stroke_inter  stroke_duration
0         8.917            1.062
1        20.879            0.786
2        11.726            0.599
y_test_f:
 0    0
1    0
2    0
3    0
4    0
5    0
6    0
7    0
8    0
9    0
Name: user, dtype: int64
x_test_f_shape:
 (10, 30)
y_test_f_len:
 10

In [163]:
x_train

,stroke_inter,stroke_duration,start_x,start_y,stop_x,stop_y,direct_ete_distance,mean_result_leng,direct_ete_line,20_pairwise_v,...,ave_direction,length_trajectory,ratio_ete,ave_v,5points_m_acc,m_stroke_press,m_stroke_area_cover,finger_orien,cd_finger_orien,phone_orien
5840,0.218,0.110,16.679,-42.515,18.096,-39.136,3.6645,0.87074,1.1737,11.65300,...,0.91708,3.6888,0.99342,33.5350,716.800,0.17647,0.100000,0.0,0,1
6077,8.860,0.585,23.329,-43.714,24.855,-41.207,2.9353,0.68240,1.0240,0.00000,...,0.66222,3.3186,0.88449,5.6728,-461.220,0.18431,0.066667,0.0,0,1
5991,4.499,0.503,23.656,-43.932,24.092,-34.993,8.9497,0.83902,1.5221,6.30560,...,1.44330,9.1897,0.97388,18.2700,-1219.100,0.16863,0.100000,0.0,0,1
5916,0.707,0.409,24.855,-45.458,25.618,-33.685,11.7980,0.92836,1.5061,16.35000,...,1.37800,12.0460,0.97939,29.4530,-57.149,0.16471,0.088889,0.0,0,1
5882,1.248,0.305,24.637,-42.951,27.253,-34.339,9.0007,0.88318,1.2759,12.07700,...,1.03580,9.3064,0.96715,30.5130,-230.920,0.19216,0.088889,0.0,0,1
6191,1.346,0.124,26.599,-45.022,27.362,-32.813,12.2330,0.82836,1.5084,70.16800,...,1.24530,12.4260,0.98450,100.2100,46.814,0.20000,0.088889,0.0,0,1
6187,12.145,0.358,25.618,-49.056,25.509,-42.188,6.8687,0.78921,1.5867,0.00000,...,1.23090,6.9474,0.98867,19.4060,-126.070,0.19608,0.088889,0.0,0,1
5782,0.655,0.212,23.983,-41.098,26.163,-27.580,13.6920,0.91858,1.4109,57.55400,...,1.28870,13.7580,0.99522,64.8960,122.210,0.17255,0.077778,0.0,0,1
6133,1.537,0.359,26.163,-45.349,27.253,-38.918,6.5235,0.84712,1.4029,2.86880,...,1.15700,6.6059,0.98752,18.4010,76.193,0.17255,0.133330,0.0,0,1
5823,3.054,0.275,24.746,-48.511,26.054,-39.790,8.8186,0.91654,1.4219,6.62300,...,1.31020,8.9532,0.98497,32.5570,-361.750,0.21176,0.077778,0.0,0,1
6146,8.554,0.359,24.201,-46.439,27.689,-36.628,10.4130,0.81402,1.2292,8.59520,...,1.14930,10.7520,0.96847,29.9490,-417.060,0.18431,0.088889,0.0,0,1
6035,1.392,0.355,23.111,-43.932,23.329,-40.117,3.8217,0.70771,1.5137,0.25955,...,1.27460,4.0161,0.95160,11.3130,-204.120,0.16078,0.088889,0.0,0,1
6117,13.531,0.456,28.125,-40.880,29.870,-31.941,9.1076,0.78178,1.3781,8.80310,...,1.27650,9.7450,0.93460,21.3710,-388.080,0.21961,0.088889,0.0,0,1
5748,2.074,0.190,34.121,-46.767,34.121,-37.173,9.5931,0.62924,1.5708,10.03300,...,1.38970,9.8564,0.97329,51.8760,-1419.900,0.07451,0.055556,0.0,0,1
6167,1.159,0.089,25.400,-46.548,25.509,-39.027,7.5227,0.79008,1.5563,30.01000,...,1.24220,7.5433,0.99727,84.7560,2307.100,0.16863,0.077778,0.0,0,1
5894,2.009,0.386,23.220,-47.530,23.874,-41.207,6.3565,0.60626,1.4677,5.45070,...,1.25830,7.1524,0.88872,18.5300,112.960,0.19608,0.088889,0.0,0,1
6052,0.749,0.401,24.419,-42.297,28.670,-27.798,15.1090,0.94548,1.2856,15.67000,...,1.24160,15.3650,0.98334,38.3170,-775.120,0.17647,0.111110,0.0,0,1
5836,0.916,0.185,26.163,-45.894,28.561,-35.429,10.7370,0.92523,1.3455,48.61600,...,1.23270,10.7700,0.99694,58.2140,-1108.600,0.20784,0.100000,0.0,0,1
5924,0.609,0.337,25.291,-46.658,28.125,-30.633,16.2740,0.92211,1.3957,11.19900,...,1.26830,16.6680,0.97632,49.4610,278.230,0.21176,0.111110,0.0,0,1
5835,0.634,0.208,26.054,-45.458,28.125,-36.301,9.3884,0.90587,1.3483,32.75700,...,1.27110,9.4854,0.98978,45.6030,35.476,0.20784,0.100000,0.0,0,1
5923,0.654,0.371,26.163,-49.601,27.253,-34.339,15.3010,0.88200,1.4995,9.99410,...,1.29750,15.6860,0.97542,42.2810,583.580,0.20392,0.100000,0.0,0,1
5881,10.464,0.376,21.803,-47.094,23.547,-41.861,5.5157,0.79509,1.2490,7.88480,...,1.09980,6.0142,0.91710,15.9950,-40.106,0.19216,0.088889,0.0,0,1
6014,0.776,0.506,24.637,-46.221,27.035,-31.941,14.4810,0.89382,1.4044,10.94700,...,1.25020,14.6830,0.98620,29.0180,-528.130,0.18431,0.088889,0.0,0,1
5992,2.544,0.446,23.329,-45.131,24.528,-39.354,5.9008,0.83572,1.3662,6.35900,...,1.25670,6.3907,0.92335,14.3290,206.360,0.15686,0.111110,0.0,0,1
5954,0.723,0.425,24.964,-40.335,27.253,-27.689,12.8510,0.70249,1.3917,7.43990,...,1.12100,13.8270,0.92942,32.5340,-216.340,0.24314,0.111110,0.0,0,1
5844,0.557,0.333,24.092,-44.913,25.727,-29.979,15.0240,0.88356,1.4617,21.26900,...,1.28620,15.3740,0.97721,46.1690,-23.528,0.20392,0.111110,0.0,0,1
5872,0.930,0.326,23.329,-46.112,24.855,-39.790,6.5043,0.91520,1.3339,9.65800,...,1.16810,6.6843,0.97308,20.5040,-258.470,0.22353,0.088889,0.0,0,1
5974,1.494,0.502,23.111,-46.221,24.855,-39.572,6.8747,0.84409,1.3143,6.41250,...,1.25930,7.2728,0.94526,14.4880,-489.220,0.18431,0.088889,0.0,0,1
5852,6.217,0.448,26.381,-34.121,28.125,-27.362,6.9802,0.84026,1.3182,6.06020,...,1.29240,7.2867,0.95795,16.2650,371.370,0.23529,0.111110,0.0,0,1
5900,7.383,0.322,25.182,-46.003,25.727,-40.335,5.6948,0.69852,1.4749,2.72530,...,1.08570,6.0871,0.93555,18.9040,-343.440,0.20000,0.088889,0.0,0,1
6097,1.046,0.127,24.092,-42.406,25.727,-31.614,10.9150,0.85218,1.4204,29.61400,...,1.18430,10.9340,0.99828,86.0960,-2136.100,0.20392,0.088889,0.0,0,1
5967,0.818,0.425,20.930,-46.330,21.803,-38.918,7.4640,0.82453,1.4537,0.60563,...,1.19300,7.5024,0.99488,17.6530,-303.170,0.21569,0.088889,0.0,0,1
6158,0.591,0.173,25.291,-47.639,25.073,-36.955,10.6850,0.86230,1.5912,46.95200,...,1.43330,10.7170,0.99708,61.9470,-1470.100,0.17647,0.088889,0.0,0,1
6181,0.685,0.186,25.291,-47.748,28.125,-31.287,16.7030,0.91146,1.4003,62.92300,...,1.31300,16.8360,0.99209,90.5180,1286.600,0.18039,0.088889,0.0,0,1
5982,0.947,0.358,23.111,-43.060,23.765,-37.827,5.2733,0.79915,1.4464,6.54470,...,1.36940,5.4861,0.96121,15.3240,-206.840,0.19216,0.088889,0.0,0,1
6110,0.927,0.355,25.836,-44.804,29.433,-31.287,13.9880,0.91178,1.3107,14.47800,...,1.16290,14.1610,0.98777,39.8910,-655.090,0.18431,0.066667,0.0,0,1
6073,5.861,0.356,23.547,-43.387,24.419,-38.809,4.6609,0.73876,1.3826,5.45060,...,1.22720,4.9260,0.94617,13.8370,-825.280,0.14118,0.077778,0.0,0,1
5803,0.907,0.342,25.727,-43.932,28.779,-31.505,12.7970,0.93085,1.3299,13.57400,...,1.21140,12.9280,0.98985,37.8010,220.420,0.18824,0.088889,0.0,0,1
6049,2.199,0.370,23.002,-44.259,24.092,-38.373,5.9868,0.84316,1.3877,1.40150,...,1.11310,6.0929,0.98258,16.4670,-624.570,0.17255,0.088889,0.0,0,1
5979,9.291,0.605,22.021,-47.421,24.419,-39.245,8.5205,0.93096,1.2855,10.62600,...,1.27440,8.8829,0.95920,14.6820,298.490,0.18039,0.077778,0.0,0,1

In [164]:
x_test

,stroke_inter,stroke_duration,start_x,start_y,stop_x,stop_y,direct_ete_distance,mean_result_leng,direct_ete_line,20_pairwise_v,...,ave_direction,length_trajectory,ratio_ete,ave_v,5points_m_acc,m_stroke_press,m_stroke_area_cover,finger_orien,cd_finger_orien,phone_orien
0,0.966,0.355,25.0730,-45.458,27.03500,-36.4100,9.2584,0.92748,1.35720,13.1880,...,1.24890,9.4862,0.97599,26.7220,-252.420,0.21961,0.111110,0.0000,0,1
1,0.755,0.200,26.0540,-47.748,28.45200,-39.2450,8.8348,0.92729,1.29590,38.1500,...,1.19490,8.9382,0.98843,44.6910,757.730,0.19608,0.066667,0.0000,0,1
2,2.998,0.288,24.2010,-45.022,24.52800,-40.4440,4.5902,0.76068,1.49950,5.2170,...,1.30420,4.9003,0.93673,17.0150,-53.995,0.16863,0.088889,0.0000,0,1
3,0.910,0.372,25.0730,-47.530,25.50900,-34.9930,12.5440,0.89390,1.53600,14.4140,...,1.36020,12.9030,0.97217,34.6860,-276.960,0.20000,0.088889,0.0000,0,1
4,0.699,0.343,26.0540,-44.477,28.56100,-29.7610,14.9290,0.84322,1.40200,9.5990,...,1.16290,15.5120,0.96238,45.2250,-474.500,0.21176,0.100000,0.0000,0,1
5,2.033,0.586,23.7650,-44.041,25.72700,-38.0450,6.3086,0.77797,1.25450,4.7975,...,1.00790,7.0889,0.88994,12.0970,120.890,0.15294,0.088889,0.0000,0,1
6,11.559,0.317,25.7270,-45.894,26.16300,-38.9180,6.9904,0.81753,1.50840,2.3125,...,1.19540,7.0491,0.99167,22.2370,62.386,0.19608,0.111110,0.0000,0,1
7,1.274,0.370,23.7650,-46.767,24.63700,-39.7900,7.0311,0.87986,1.44640,9.3132,...,1.24970,7.2062,0.97570,19.4760,-961.110,0.20000,0.133330,0.0000,0,1
8,1.869,1.606,24.5280,-41.970,27.14400,-33.2490,9.1050,0.48590,1.27930,1.9622,...,0.83751,19.3560,0.47041,12.0520,-47.148,0.20784,0.111110,0.0000,0,1
9,0.694,0.071,23.5470,-38.264,25.61800,-26.8170,11.6320,0.83039,1.39180,46.4650,...,1.09490,11.6390,0.99941,163.9300,-52025.000,0.18824,0.077778,0.0000,0,1
10,8.917,1.062,0.8721,-54.615,0.54506,-45.4580,9.1629,0.70150,1.60650,2.0444,...,1.34780,10.1170,0.90568,9.5265,0.000,0.32000,0.100000,0.0000,0,1
11,20.879,0.786,20.8210,-47.312,31.39600,-34.5570,16.5680,0.83685,0.87859,12.1200,...,0.85592,18.4650,0.89724,23.4930,101.150,0.27451,0.166670,0.0000,0,1
12,11.726,0.599,7.3039,-33.685,6.21370,-17.0060,16.7150,0.92737,1.63610,10.9010,...,1.57870,16.8310,0.99306,28.0990,1146.100,0.35000,0.088889,0.0000,0,1
13,10.352,1.027,5.0397,-40.821,4.03170,-33.0600,7.8263,0.73661,1.69990,3.4511,...,1.46390,8.5492,0.91544,8.3245,0.000,0.60000,0.044444,0.0000,0,1
14,1.158,0.675,4.1425,-22.675,3.48840,-18.3140,4.4093,0.74123,1.71970,3.5283,...,1.56910,4.8541,0.90837,7.1912,110.090,0.48000,0.133330,1.5708,0,2
15,5.957,0.747,18.6470,-44.349,23.68700,-19.5540,25.3020,0.90019,1.37030,13.2760,...,1.26170,26.2930,0.96232,35.1980,-969.650,0.49000,0.044444,0.0000,0,1
16,30.198,0.866,24.5940,-40.317,24.99700,-19.3520,20.9690,0.92439,1.55160,12.7990,...,1.47740,21.1670,0.99064,24.4420,-164.720,0.26000,0.044444,0.0000,0,1
17,5.150,4.537,17.6390,-41.729,24.19000,-24.0900,18.8160,0.76632,1.21520,0.0000,...,0.87196,21.1060,0.89152,4.6519,52.698,0.11765,0.100000,0.0000,0,1
18,0.911,0.201,12.9730,-45.676,11.22800,-38.7000,7.1915,0.78696,1.81580,2.7715,...,1.48510,7.2141,0.99687,35.8910,835.910,0.32000,0.088889,0.0000,0,1
19,19.540,5.445,13.3050,-46.163,31.14500,-6.0476,43.9040,0.77475,1.15230,0.0000,...,0.89714,49.0080,0.89585,9.0006,205.860,0.49000,0.044444,0.0000,0,1

In [ ]:
# 何度行っても同じ結果が得られる

In [204]:
# query()の動作確認
list_test = [1,2,3,4,5,6,7]
df_sample = pd.DataFrame({'val': [10,20,30,20,50, 60, 70],
                          'name': ['ABC', 'BCD', 'CDE', 'EDC', 'CBA', 'CNN', 'RNN'],
                          'date': [1,2,3,4,4,6,7]})
df_sample.query('1<= date <= 8')

   val name  date
0   10  ABC     1
1   20  BCD     2
2   30  CDE     3
3   20  EDC     4
4   50  CBA     4
5   60  CNN     6
6   70  RNN     7

In [272]:
flag_df = pd.DataFrame([['aa', 'ab', 'ac', 'ad', 'ba', 'bb', 'bc', 'bd', 'ca', 'cb', 'cc', 'cd', 'da', 'db', 'dc', 'dd'],
                      [11, 12, 13, 14, 21, 22, 23, 24, 31, 32, 33, 34, 41, 42, 43,44 ],
                       ['aa', 'ab', 'ac', 'ad', 'ba', 'bb', 'bc', 'bd', 'ca', 'cb', 'cc', 'cd', 'da', 'db', 'dc', 'dd'],
                       [None, None, None, None, None,None, 'NY', 'CA', 'TX', 'CA',None, None, None, None, None,None]])

In [273]:
flag_df = flag_df.T

In [274]:
flag_df.columns = ['name', 'values', 'name_low','test']

In [275]:
flag_df

   name values name_low  test
0    aa     11       aa  None
1    ab     12       ab  None
2    ac     13       ac  None
3    ad     14       ad  None
4    ba     21       ba  None
5    bb     22       bb  None
6    bc     23       bc    NY
7    bd     24       bd    CA
8    ca     31       ca    TX
9    cb     32       cb    CA
10   cc     33       cc  None
11   cd     34       cd  None
12   da     41       da  None
13   db     42       db  None
14   dc     43       dc  None
15   dd     44       dd  None

In [276]:
flag_df['name'] = flag_df['name'].str.upper()

In [277]:
flag_df

   name values name_low  test
0    AA     11       aa  None
1    AB     12       ab  None
2    AC     13       ac  None
3    AD     14       ad  None
4    BA     21       ba  None
5    BB     22       bb  None
6    BC     23       bc    NY
7    BD     24       bd    CA
8    CA     31       ca    TX
9    CB     32       cb    CA
10   CC     33       cc  None
11   CD     34       cd  None
12   DA     41       da  None
13   DB     42       db  None
14   DC     43       dc  None
15   DD     44       dd  None

In [280]:
flag_df = flag_df.fillna({'test':'No_Title'})
flag_df

   name values name_low      test
0    AA     11       aa  No_Title
1    AB     12       ab  No_Title
2    AC     13       ac  No_Title
3    AD     14       ad  No_Title
4    BA     21       ba  No_Title
5    BB     22       bb  No_Title
6    BC     23       bc        NY
7    BD     24       bd        CA
8    CA     31       ca        TX
9    CB     32       cb        CA
10   CC     33       cc  No_Title
11   CD     34       cd  No_Title
12   DA     41       da  No_Title
13   DB     42       db  No_Title
14   DC     43       dc  No_Title
15   DD     44       dd  No_Title

In [286]:
# クエリ削除 https://note.nkmk.me/python-urllib-parse-query-string/
from urllib import parse
def remove_all_query(url):
    return parse.urlunparse(parse.urlparse(url)._replace(query=None))
url='https://torina.top/quick/?quick-text=python'
print(remove_all_query(url))

https://torina.top/quick/

In [1]:
import datetime

In [2]:
now = datetime.datetime.now()
now

datetime.datetime(2020, 11, 11, 22, 41, 44, 778633)

In [4]:
now2 = ['01/01/2019']
type(now2[0])
now3 =

str

In [270]:
now.strftime('%Y-%m-%d')

'2020-11-06'

In [300]:
# https://torina.top/detail/305/
from urllib import parse
urls = [
    'https://torina.top/quick/?quick-text=python',
    'https://torina.top/quick/?quick-text=django',
    'https://torina.top/quick/?quick-text=kivy',
    'https://torina.top/quick/?quick-text=bootstrap',
    'https://torina.top/quick/?quick-text=centos7',
    'https://torina.top/quick/?quick-text=python',
    'https://torina.top/quick/?quick-text=django',
    'https://torina.top/quick/?quick-text=kivy',
    'https://torina.top/quick/?quick-text=bootstrap',
    'https://torina.top/quick/?quick-text=centos7',
    'https://torina.top/quick/?quick-text=python',
    'https://torina.top/quick/?quick-text=django',
    'https://torina.top/quick/?quick-text=kivy',
    'https://torina.top/quick/?quick-text=bootstrap',
    'https://torina.top/quick/?quick-text=centos7',
    'https://torina.top/quick/?quick-text=python',
]
url = pd.DataFrame(urls)
url

                                                 0
0      https://torina.top/quick/?quick-text=python
1      https://torina.top/quick/?quick-text=django
2        https://torina.top/quick/?quick-text=kivy
3   https://torina.top/quick/?quick-text=bootstrap
4     https://torina.top/quick/?quick-text=centos7
5      https://torina.top/quick/?quick-text=python
6      https://torina.top/quick/?quick-text=django
7        https://torina.top/quick/?quick-text=kivy
8   https://torina.top/quick/?quick-text=bootstrap
9     https://torina.top/quick/?quick-text=centos7
10     https://torina.top/quick/?quick-text=python
11     https://torina.top/quick/?quick-text=django
12       https://torina.top/quick/?quick-text=kivy
13  https://torina.top/quick/?quick-text=bootstrap
14    https://torina.top/quick/?quick-text=centos7
15     https://torina.top/quick/?quick-text=python

In [304]:
flag_df2 = pd.concat([flag_df, url], axis=1)
flag_df2=flag_df2.rename(columns={0:'url'})
flag_df2

,name,values,name_low,test,url
0,AA,11,aa,No_Title,https://torina.top/quick/?quick-text=python
1,AB,12,ab,No_Title,https://torina.top/quick/?quick-text=django
2,AC,13,ac,No_Title,https://torina.top/quick/?quick-text=kivy
3,AD,14,ad,No_Title,https://torina.top/quick/?quick-text=bootstrap
4,BA,21,ba,No_Title,https://torina.top/quick/?quick-text=centos7
5,BB,22,bb,No_Title,https://torina.top/quick/?quick-text=python
6,BC,23,bc,NY,https://torina.top/quick/?quick-text=django
7,BD,24,bd,CA,https://torina.top/quick/?quick-text=kivy
8,CA,31,ca,TX,https://torina.top/quick/?quick-text=bootstrap
9,CB,32,cb,CA,https://torina.top/quick/?quick-text=centos7
10,CC,33,cc,No_Title,https://torina.top/quick/?quick-text=python
11,CD,34,cd,No_Title,https://torina.top/quick/?quick-text=django
12,DA,41,da,No_Title,https://torina.top/quick/?quick-text=kivy
13,DB,42,db,No_Title,https://torina.top/quick/?quick-text=bootstrap
14,DC,43,dc,No_Title,https://torina.top/quick/?quick-text=centos7
15,DD,44,dd,No_Title,https://torina.top/quick/?quick-text=python

In [306]:
flag_df2['url_new'] = flag_df2['url'].apply(lambda url: parse.urlunparse(parse.urlparse(url)._replace(query=None)))

In [307]:
flag_df2

,name,values,name_low,test,url,url_new
0,AA,11,aa,No_Title,https://torina.top/quick/?quick-text=python,https://torina.top/quick/
1,AB,12,ab,No_Title,https://torina.top/quick/?quick-text=django,https://torina.top/quick/
2,AC,13,ac,No_Title,https://torina.top/quick/?quick-text=kivy,https://torina.top/quick/
3,AD,14,ad,No_Title,https://torina.top/quick/?quick-text=bootstrap,https://torina.top/quick/
4,BA,21,ba,No_Title,https://torina.top/quick/?quick-text=centos7,https://torina.top/quick/
5,BB,22,bb,No_Title,https://torina.top/quick/?quick-text=python,https://torina.top/quick/
6,BC,23,bc,NY,https://torina.top/quick/?quick-text=django,https://torina.top/quick/
7,BD,24,bd,CA,https://torina.top/quick/?quick-text=kivy,https://torina.top/quick/
8,CA,31,ca,TX,https://torina.top/quick/?quick-text=bootstrap,https://torina.top/quick/
9,CB,32,cb,CA,https://torina.top/quick/?quick-text=centos7,https://torina.top/quick/
10,CC,33,cc,No_Title,https://torina.top/quick/?quick-text=python,https://torina.top/quick/
11,CD,34,cd,No_Title,https://torina.top/quick/?quick-text=django,https://torina.top/quick/
12,DA,41,da,No_Title,https://torina.top/quick/?quick-text=kivy,https://torina.top/quick/
13,DB,42,db,No_Title,https://torina.top/quick/?quick-text=bootstrap,https://torina.top/quick/
14,DC,43,dc,No_Title,https://torina.top/quick/?quick-text=centos7,https://torina.top/quick/
15,DD,44,dd,No_Title,https://torina.top/quick/?quick-text=python,https://torina.top/quick/

In [310]:
url='https://torina.top/quick/?quick-text=python'
parse_result = parse.urlparse(url)
print(parse_result)

ParseResult(scheme='https', netloc='torina.top', path='/quick/', params='', query='quick-text=python', fragment='')

In [311]:
parse_result.netloc

'torina.top/quick/'

In [312]:
flag_df2['domain'] = flag_df2['url_new'].apply(lambda url: parse.urlparse(url).netloc)

In [313]:
flag_df2

,name,values,name_low,test,url,url_new,domain
0,AA,11,aa,No_Title,https://torina.top/quick/?quick-text=python,https://torina.top/quick/,torina.top
1,AB,12,ab,No_Title,https://torina.top/quick/?quick-text=django,https://torina.top/quick/,torina.top
2,AC,13,ac,No_Title,https://torina.top/quick/?quick-text=kivy,https://torina.top/quick/,torina.top
3,AD,14,ad,No_Title,https://torina.top/quick/?quick-text=bootstrap,https://torina.top/quick/,torina.top
4,BA,21,ba,No_Title,https://torina.top/quick/?quick-text=centos7,https://torina.top/quick/,torina.top
5,BB,22,bb,No_Title,https://torina.top/quick/?quick-text=python,https://torina.top/quick/,torina.top
6,BC,23,bc,NY,https://torina.top/quick/?quick-text=django,https://torina.top/quick/,torina.top
7,BD,24,bd,CA,https://torina.top/quick/?quick-text=kivy,https://torina.top/quick/,torina.top
8,CA,31,ca,TX,https://torina.top/quick/?quick-text=bootstrap,https://torina.top/quick/,torina.top
9,CB,32,cb,CA,https://torina.top/quick/?quick-text=centos7,https://torina.top/quick/,torina.top
10,CC,33,cc,No_Title,https://torina.top/quick/?quick-text=python,https://torina.top/quick/,torina.top
11,CD,34,cd,No_Title,https://torina.top/quick/?quick-text=django,https://torina.top/quick/,torina.top
12,DA,41,da,No_Title,https://torina.top/quick/?quick-text=kivy,https://torina.top/quick/,torina.top
13,DB,42,db,No_Title,https://torina.top/quick/?quick-text=bootstrap,https://torina.top/quick/,torina.top
14,DC,43,dc,No_Title,https://torina.top/quick/?quick-text=centos7,https://torina.top/quick/,torina.top
15,DD,44,dd,No_Title,https://torina.top/quick/?quick-text=python,https://torina.top/quick/,torina.top

In [314]:
flag_df3 = flag_df2.drop('url', axis=1)
flag_df3

   name values name_low      test                    url_new      domain
0    AA     11       aa  No_Title  https://torina.top/quick/  torina.top
1    AB     12       ab  No_Title  https://torina.top/quick/  torina.top
2    AC     13       ac  No_Title  https://torina.top/quick/  torina.top
3    AD     14       ad  No_Title  https://torina.top/quick/  torina.top
4    BA     21       ba  No_Title  https://torina.top/quick/  torina.top
5    BB     22       bb  No_Title  https://torina.top/quick/  torina.top
6    BC     23       bc        NY  https://torina.top/quick/  torina.top
7    BD     24       bd        CA  https://torina.top/quick/  torina.top
8    CA     31       ca        TX  https://torina.top/quick/  torina.top
9    CB     32       cb        CA  https://torina.top/quick/  torina.top
10   CC     33       cc  No_Title  https://torina.top/quick/  torina.top
11   CD     34       cd  No_Title  https://torina.top/quick/  torina.top
12   DA     41       da  No_Title  https://torina.top/quick/  torina.top
13   DB     42       db  No_Title  https://torina.top/quick/  torina.top
14   DC     43       dc  No_Title  https://torina.top/quick/  torina.top
15   DD     44       dd  No_Title  https://torina.top/quick/  torina.top

In [315]:
flag_df3 = flag_df3[~flag_df3['test'].isin(['CA'])]
flag_df3

   name values name_low      test                    url_new      domain
0    AA     11       aa  No_Title  https://torina.top/quick/  torina.top
1    AB     12       ab  No_Title  https://torina.top/quick/  torina.top
2    AC     13       ac  No_Title  https://torina.top/quick/  torina.top
3    AD     14       ad  No_Title  https://torina.top/quick/  torina.top
4    BA     21       ba  No_Title  https://torina.top/quick/  torina.top
5    BB     22       bb  No_Title  https://torina.top/quick/  torina.top
6    BC     23       bc        NY  https://torina.top/quick/  torina.top
8    CA     31       ca        TX  https://torina.top/quick/  torina.top
10   CC     33       cc  No_Title  https://torina.top/quick/  torina.top
11   CD     34       cd  No_Title  https://torina.top/quick/  torina.top
12   DA     41       da  No_Title  https://torina.top/quick/  torina.top
13   DB     42       db  No_Title  https://torina.top/quick/  torina.top
14   DC     43       dc  No_Title  https://torina.top/quick/  torina.top
15   DD     44       dd  No_Title  https://torina.top/quick/  torina.top

In [316]:
flag_df4 = flag_df3.sample(frac=1, random_state=0).reset_index(drop=True)
flag_df4

   name values name_low      test                    url_new      domain
0    CC     33       cc  No_Title  https://torina.top/quick/  torina.top
1    BC     23       bc        NY  https://torina.top/quick/  torina.top
2    BA     21       ba  No_Title  https://torina.top/quick/  torina.top
3    DB     42       db  No_Title  https://torina.top/quick/  torina.top
4    AC     13       ac  No_Title  https://torina.top/quick/  torina.top
5    DD     44       dd  No_Title  https://torina.top/quick/  torina.top
6    CD     34       cd  No_Title  https://torina.top/quick/  torina.top
7    AB     12       ab  No_Title  https://torina.top/quick/  torina.top
8    CA     31       ca        TX  https://torina.top/quick/  torina.top
9    DA     41       da  No_Title  https://torina.top/quick/  torina.top
10   AD     14       ad  No_Title  https://torina.top/quick/  torina.top
11   AA     11       aa  No_Title  https://torina.top/quick/  torina.top
12   BB     22       bb  No_Title  https://torina.top/quick/  torina.top
13   DC     43       dc  No_Title  https://torina.top/quick/  torina.top

In [320]:
# 複数条件のソート
flag_df5 = flag_df4.sort_values(["test","values"],ascending=[True,True]).reset_index()
flag_df5

,index,name,values,name_low,test,url_new,domain
0,1,BC,23,bc,NY,https://torina.top/quick/,torina.top
1,11,AA,11,aa,No_Title,https://torina.top/quick/,torina.top
2,7,AB,12,ab,No_Title,https://torina.top/quick/,torina.top
3,4,AC,13,ac,No_Title,https://torina.top/quick/,torina.top
4,10,AD,14,ad,No_Title,https://torina.top/quick/,torina.top
5,2,BA,21,ba,No_Title,https://torina.top/quick/,torina.top
6,12,BB,22,bb,No_Title,https://torina.top/quick/,torina.top
7,0,CC,33,cc,No_Title,https://torina.top/quick/,torina.top
8,6,CD,34,cd,No_Title,https://torina.top/quick/,torina.top
9,9,DA,41,da,No_Title,https://torina.top/quick/,torina.top
10,3,DB,42,db,No_Title,https://torina.top/quick/,torina.top
11,13,DC,43,dc,No_Title,https://torina.top/quick/,torina.top
12,5,DD,44,dd,No_Title,https://torina.top/quick/,torina.top
13,8,CA,31,ca,TX,https://torina.top/quick/,torina.top

In [ ]:
data = ['01/01/2019']